### ISSUE TITLE
Print out Movie Year released cause sometimes they have the same title

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#10]
Print out Movie Year released cause sometimes they have the same title.
![Screenshot_2022-08-07_18-29-10](https://user-images.githubusercontent.com/95531944/183286648-c5053393-5c54-42e5-9d43-e78c7040134e.png)

**Comment by justchokingaround** [comment]
i will look into implementing it later, don't expect it very soon

**Comment by justchokingaround** [comment]
won't implement in shell, will implement it when i port the project to rust
