### ISSUE TITLE
How to use this lobster ms marvel >/dev/null is this what I paste in config? The output of mpv is just annoying to my eyes

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#100]
how ? I just want it to look like ani-cli I it is something mpv output.
![1](https://github.com/justchokingaround/lobster/assets/95531944/3986a8a8-1cc8-48e6-80f4-557290873acb)

this looks better and polished
![1](https://github.com/justchokingaround/lobster/assets/95531944/2fe895b4-caac-4ef0-bf71-1a6b421bf381)

**Comment by justchokingaround** [comment]
i could implement an option in the config for this ig

**Comment by ttx99** [comment]
thx bro cause after just two episodes terminal looks like this
![1](https://github.com/justchokingaround/lobster/assets/95531944/0b8033f1-f7e5-453b-9c1f-43c3f0341734)

**Comment by justchokingaround** [comment]
ig i'll just make it the default behavior then

**Comment by ttx99** [comment]
can you test explained corona virus s1ep1 cause it just gets stuck

**Comment by justchokingaround** [comment]
what's the show's exact name?

**Comment by justchokingaround** [comment]
video plays fine for me

**Comment by justchokingaround** [comment]
4db9d46

**Comment by justchokingaround** [comment]
00be338 makes this behavior disabled by default, you can either enable it in the config file with `quiet_output=1` or by passing the `--quiet` argument when running the script @ttx99
