### ISSUE TITLE
[feat] configurable ueberzug offsets

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#104]
**Is your feature request related to a problem? Please describe.**
For various reasons, the ueberzug previews might not appear at the right position and viewbox size. ueberzug is basically a hack, so it's not possible to test for all the ways that it doesn't work properly.

**Describe the solution you'd like**
x and y offsets and scaling in config, so that the user can adjust him self the positions and size.

**Describe alternatives you've considered**
Trying to solve this programmatically is impossible.

**Additional context**
Other applications that use ueberzug have the same problems.

**Comment by justchokingaround** [comment]
ueberzug's cmd doesn't support the `width` and `height` arguments, so ig i'm left with no choice, and i will have to implement the fifo approach

![image](https://github.com/justchokingaround/lobster/assets/44473782/b00913fc-560c-42b9-9e60-1e64e2cb5099)

**Comment by justchokingaround** [comment]
`--max-width` and `--max-height` are not the same as `--width` and `--height`, they just set the limit, they don't scale the image, you can test it yourself by playing with the image_fzf_preview function (or whatever its name)

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/lobster/commit/c991c5a59470efa8f494bc2a690542887caec333 (undocumented, i'll do it a bit later)
