### ISSUE TITLE
[feat] option --

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#106]
**Is your feature request related to a problem? Please describe.**
Options that take a parameter interfere with the query, requiring to change the order.

**Describe the solution you'd like**
The option `--` means that stuff after it, are not to be interpreted as options. So you can put all your options at the beginning and the query after `--`

**Describe alternatives you've considered**

A simple alternative would be to have an option for the query.

**Comment by justchokingaround** [comment]
yes, however it lacks support for long args, and without bashisms it just doesn't work properly
