### ISSUE TITLE
[refactor] mv UB_PID_FILE and SOCKET inside /tmp/lobster

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#107]
you forgot to move ueberzugpp stuff in /tmp/lobster

edit: changed `/etc/lobster` to `/tmp/lobster`

**Comment by justchokingaround** [comment]
I implemented the fzf preview using fifo, it should be more efficient and less error proof, please test it out (currently on the `fix-subs` branch) https://github.com/justchokingaround/lobster/commit/de27e1e0e6aaea91efca620c5eb7b12222ebd2cb

**Comment by justchokingaround** [comment]
@pirate486743186 could you please test it out by running:
```sh
sh <(curl -s https://raw.githubusercontent.com/justchokingaround/lobster-extra/main/lobster-tests.sh) -r https://raw.githubusercontent.com/justchokingaround/lobster/fix-subs/lobster.sh -t 2
```
there is no need to install anything, everything will be done automatically

**Comment by justchokingaround** [comment]
so does it work better/faster than the old approach?
could you please open a new issue for movie which aren't displayed if they don't have an image (with an example)

**Comment by justchokingaround** [comment]
then i might revert the changes, since it causes a bug with wayland as the ueberzug_output

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/lobster/commit/54721c4a505cfb941939206c511ff17af5d214a9 (on the dev branch)

**Comment by justchokingaround** [comment]
merged this change into main, closing this now
