### ISSUE TITLE
[feature] ueberzugpp is slow

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#111]
In ranger(fifo), it's basically instantaneous. In lobster you get to see the "loading" text and you have to wait.

**Comment by justchokingaround** [comment]
i could try to implement that

**Comment by justchokingaround** [comment]
could you please give me a sample ranger config so i could look at the implementation that uses ueberzug with fifo?

**Comment by justchokingaround** [comment]
from my testing with ranger (which uses the fifo approach) and lf (using lfub, which sends commands to the ueberzug layer, the same way as lobster currently does), i couldn't see any difference in the speed at which it was displayed. i will still take a look at the fifo implementation, it seems to be a cleaner approach

**Comment by justchokingaround** [comment]
https://github.com/ranger/ranger/blob/1a007158cef1279df68d0e8567b126def6b68046/ranger/ext/img_display.py#L897-L955

this looks like the same approach i'm currently using

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/assets/44473782/08d21460-9f4e-408a-983a-ee6d3c0aa229
