### ISSUE TITLE
if parameter starts with -, it's an option

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#113]
**Is your feature request related to a problem? Please describe.**
There's a mess with the options that take parameters. If the user doesn't add the parameter, the next option is treated as parameter.

**Describe the solution you'd like**
If the parameter starts with -, then reject it and use the default value. The shift should also be correct.

**Comment by justchokingaround** [comment]
878ba66 should cover this, please test it

**Comment by justchokingaround** [comment]
there always are, i need to create a proper testing workflow instead of (mostly) blindly committing to the main branch. it's in my todo list, i'll eventually get to it

**Comment by justchokingaround** [comment]
closing in favor of https://github.com/justchokingaround/lobster/issues/106
