### ISSUE TITLE
There are some videos that gets stuck and buffer forever 

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#115]
![1](https://github.com/justchokingaround/lobster/assets/95531944/741c36a4-f2f6-47d7-b222-cc6d2abab4bb)
![2](https://github.com/justchokingaround/lobster/assets/95531944/849df2ad-3977-48ca-934c-034a85091cd0)

changing provider still the same

**Comment by justchokingaround** [comment]
works fine on my side, can't reproduce. try relaunching it

![image](https://github.com/justchokingaround/lobster/assets/44473782/7f843635-c0a3-4b22-8c3a-dacc2299a976)

**Comment by justchokingaround** [comment]
does it work in the browser? what are your mpv cache settings? (`~/.config/mpv/mpv.conf`)

**Comment by ttx99** [comment]
i dont have cache settings 
yes, in browser it plays well

can you paste your cache settings

**Comment by ttx99** [comment]
hwdec=vaapi
profile=gpu-hq
vo=gpu
gpu-api=vulkan 
window-maximized=yes
sub-bold=yes
deinterlace=yes
script-opts=ytdl_hook-ytdl_path=/home/mac99/.local/bin/yt-dlp

**Comment by justchokingaround** [comment]
try these settings

```
hls-bitrate=max
cache=yes
demuxer-max-bytes=1GiB
demuxer-max-back-bytes=100MiB
demuxer-readahead-secs=20
```

**Comment by ttx99** [comment]
well I guess its my internet then
![1](https://github.com/justchokingaround/lobster/assets/95531944/ad923dc0-6c9c-4ff2-9da6-be348cf735e0)

**Comment by justchokingaround** [comment]
yes, that could be the reason. can you send me the video link, by running the following command while the video is playing:
```sh
echo '{ "command": ["get_property", "path"] }' | socat - /tmp/mpvsocket | sed -nE "s@.*\"data\":\"([^\"]*)\".*@\1@p"
```

**Comment by ttx99** [comment]
yeah thx man

**Comment by justchokingaround** [comment]
yep, cannot reproduce, works fine for me:

https://github.com/justchokingaround/lobster/assets/44473782/32b21722-6b8f-40a5-844b-180b616c4f06
