### ISSUE TITLE
how do I install html-xml utils in windows?

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#116]
how to install html-xml utils in windows 10?

**Comment by justchokingaround** [comment]
you can't, it does not exist, hence why i'm working on rewriting it in powershell

**Comment by justchokingaround** [comment]
if you really want it to work on windows right now, you could manually patch the script by removing all of the instances where `hxunent` is used, and removing that dependency check

**Comment by ttx99** [comment]
you guys know how to make and where to place mpv config on windows 10 installed via scoop?

**Comment by justchokingaround** [comment]
%appdata% and search for the mpv folder and then put it there

**Comment by ttx99** [comment]
yes, but what is the config filename? is it mpv.conf or txt? you have screen shot?

**Comment by justchokingaround** [comment]
mpv.conf yes. you can also have other files like input.conf for keybinds, a shaders directory (folder), a scripts directory and a script-opts directory (for script settings). but the main config file is mpv.conf

**Comment by ttx99** [comment]
btw there is no mpv folder there is just local, local low and Roaming. I assume i need to create?

**Comment by justchokingaround** [comment]
yes

**Comment by ttx99** [comment]
--vo=gpu
--hwdec=vaapi
--profile=gpu-hq
--gpu-api=vulkan
--sub-bold=yes
--window-maximized=yes

the video is still not maximized im trying ani-cli like old anime aspect ratio

**Comment by justchokingaround** [comment]
remove tbe leading `--` for all the options, you're not supposed to include them

**Comment by ttx99** [comment]
C:\Users\user\AppData\mpv 

is this right?

**Comment by justchokingaround** [comment]
could be, yes. it's not always the same location afaik

**Comment by ttx99** [comment]
config still wont take effect  gg

**Comment by ttx99** [comment]
> if you really want it to work on windows right now, you could manually patch the script by removing all of the instances where `hxunent` is used, and removing that dependency check

and btw dude to answer this topic If I cant even make mpv config to work. I rather wait for you to do it 😃  your pro at this .

**Comment by justchokingaround** [comment]
@ttx99 mentioned it in the discord server a few days ago, but completely forgot to do it here. this install should work on windows, if u have fzf and mpv installed:
```sh
curl -O https://raw.githubusercontent.com/justchokingaround/lobster/windows-support/lobster.sh
chmod +x lobster.sh
sed -i 's/ | hxunent//g; /command -v "hxunent"/d' lobster.sh
cp lobster.sh /usr/bin/lobster
```
(it's a good idea to run the terminal in administrator mode for installing, as u might get a permission denied otherwise)
also if it says mpv not found, this should fix it, if you installed mpv through scoop:
```sh
ln -sf $(which mpv.exe) /usr/bin/mpv
```
