### ISSUE TITLE
Suddenly the script is so slow and subtitles dont work(sometimes work).

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#12]
Vpn and no vpn still the same  topgun: maverick 
![Screenshot_2022-08-21_15-18-36](https://user-images.githubusercontent.com/95531944/185780205-d2a1ac98-97f9-4ef7-9433-55df5478979b.png)
That's that embedded subtitle. I played this movie before but I wasn't able to finish it. Last time it played with English Subtitle.
![Screenshot_2022-08-21_15-19-55](https://user-images.githubusercontent.com/95531944/185780252-d6bab154-e2f7-4fa0-b3ba-98cb283a9344.png)

**Comment by justchokingaround** [comment]
can you check if you're on the latest version, that is 2.0.2?

**Comment by ttx99** [comment]
sorry damn that update. my bad
![Screenshot_2022-08-21_15-25-23](https://user-images.githubusercontent.com/95531944/185780625-cbc1fb51-5c83-499b-be79-7fa10fa9653b.png)
