### ISSUE TITLE
[feat] flag to clear history

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#120]
to clear history

**Comment by ttx99** [comment]
and observed that my history file is empty but the script presents me with a list
![1](https://github.com/justchokingaround/lobster/assets/95531944/0d4eed08-b149-45b3-98c1-102c44c130cd)
![2](https://github.com/justchokingaround/lobster/assets/95531944/662f426d-ebcb-4e15-a0e7-5684bd21c401)

**Comment by justchokingaround** [comment]
it's in `~/.local/share/lobster/lobster_history.txt` by default now

**Comment by ttx99** [comment]
its still empty 
![1](https://github.com/justchokingaround/lobster/assets/95531944/f7944f0b-6713-4515-897a-0c11f8e76359)
![2](https://github.com/justchokingaround/lobster/assets/95531944/9c3991ac-4b04-4059-a75c-df0224d9a941)

**Comment by justchokingaround** [comment]
can you send me logs and the config file you are using please?

**Comment by ttx99** [comment]
where could i find the logs again?

**Comment by ttx99** [comment]
history=0
use_external_menu=0
image_preview=0
image_config_path="$HOME/.config/rofi/styles/launcher.rasi"
subs_language="English"
player="mpv"
json_output=0
histfile="$HOME/.local/share/lobster_history.txt"
cache_dir="/tmp/lobster"
images_cache_dir="/tmp/lobster-images"
applications_dir="$HOME/.local/share/applications/lobster"
tmp_position="/tmp/lobster_position"
lobster_editor=lite-xl

**Comment by justchokingaround** [comment]
`/tmp/lobster.log`

**Comment by ttx99** [comment]
[lobster.log](https://github.com/justchokingaround/lobster/files/11712334/lobster.log)

**Comment by justchokingaround** [comment]
what's the output of
```sh
cat "$HOME/.local/share/applications/lobster/lobster_history.txt"
```

**Comment by justchokingaround** [comment]
actually, i missread the log, delete this file:
```sh
rm ~/.local/share/lobster_history.txt
```

**Comment by justchokingaround** [comment]
reopening this as a feature request for an arg that clears history

**Comment by justchokingaround** [comment]
this feature has been added in https://github.com/justchokingaround/lobster/commit/d27b012f7ae311198c95f99936e8d32c3ef3e598

**Comment by justchokingaround** [comment]
done in 0f22bad6cba1c890fc8808f468eb053be40b011c
