### ISSUE TITLE
[bug] ueberzugpp images too big and wrong position

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#122]
Did you test ueberzugpp?

**Comment by justchokingaround** [comment]
> Did you test ueberzugpp?

yes, it looks for me the same as it does on the demo, how does it look for you?

**Comment by justchokingaround** [comment]
what do you mean by that? a terminal with a small font? a reduced window size?

**Comment by justchokingaround** [comment]
ill check it out

**Comment by justchokingaround** [comment]
should be fixed in https://github.com/justchokingaround/lobster/commit/c100d9cfe35529ee7e3ccbff7ccce5311c0a534d (currently on the `fix-subs` branch)

**Comment by justchokingaround** [comment]
that makes the image completely out of the terminal for me, but that is why i give the user the opportunity to customize the positioning and scale in the config file
