### ISSUE TITLE
[bug] subtitles suddenly doesnt work anymore after update

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#123]
history=0
use_external_menu=0
image_preview=0
image_config_path="$HOME/.config/rofi/styles/launcher.rasi"
subs_language="English"
player="mpv"
json_output=0
histfile="$HOME/.local/share/lobster_history.txt"
cache_dir="/tmp/lobster"
images_cache_dir="/tmp/lobster-images"
applications_dir="$HOME/.local/share/applications/lobster"
tmp_position="/tmp/lobster_position"
lobster_editor=lite-xl

**Comment by ttx99** [comment]
pressing j wont find subs also

**Comment by justchokingaround** [comment]
This seems like a bug I introduced in 3c3506f414a140200e4dad83ee36a403997c620e, the subs aren't parsed properly

**Comment by justchokingaround** [comment]
Should be fixed in https://github.com/justchokingaround/lobster/commit/f0100f40076e66689392580199245517f5393fe4 (currently only fixed on the `fix-subs` branch)

**Comment by justchokingaround** [comment]
i'll merge it tomorrow, after some testing

**Comment by justchokingaround** [comment]
fixed in 0f22bad6cba1c890fc8808f468eb053be40b011c
