### ISSUE TITLE
[bug] ueberzug, if there's no image, the item is not listed.

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#126]
**Describe the bug**
It seams that if for what ever reason it doesn't find an image then it is not listed. This can vary randomly, so it seams to be a networking issue

**To Reproduce**

Probably bad networking will do that.

**Expected behavior**
It should still list the item without an image.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Version latest

**Comment by justchokingaround** [comment]
can you provide an example query + entry that is not displayed please?

**Comment by justchokingaround** [comment]
oh ok, i think i know what you mean

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
