### ISSUE TITLE
how to display thumbnail to the right side?

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#129]
![Screenshot_2023-06-18_18-44-22](https://github.com/justchokingaround/lobster/assets/95531944/8ff4b6f6-2f83-4836-bb76-eed62e2d66ab)

**Comment by justchokingaround** [comment]
add this to your lobster config, and play around with the values:
```sh
preview_window_size=right:60%:wrap
ueberzug_x=100
ueberzug_y=10
ueberzug_max_width=$(($(tput lines) / 2))
ueberzug_max_height=$(($(tput lines) / 2))
```
