### ISSUE TITLE
subtitles in mpv android

### ISSUE THREAD

**Issue by olivluca** [justchokingaround/lobster#13]
I tried to add 

`-e "subs" "$subs_links"
`

to the am start command for mpv/android, but it gives an error

` W Bundle  : Key subs expected Parcelable[] but value was a java.lang.String.  The default value <null> was returned.
`

The only sensible reference on how to send a parcelable with am start says [it's not possible](https://groups.google.com/g/android-platform/c/kle8S64mQdU)  but that was in 2010, maybe now it is possible?

**Comment by justchokingaround** [comment]
https://github.com/mpv-android/mpv-android/issues/587

**Comment by justchokingaround** [comment]
this is the current status for subs in mpv android, still haven't figured out how to make it work (even after downloading the subs locally)

**Comment by justchokingaround** [comment]
https://github.com/mpv-android/mpv-android/issues/427

**Comment by olivluca** [comment]
I tried https://github.com/TheGlockMisc/mpv-android-argparse but mpv [cannot read the generated configuration](https://github.com/TheGlockMisc/mpv-android-argparse/issues/5).
If I modify that script (since it removes the '\\' between "https" and ":" ) and then copy and paste the "sub-file=...." in mpv.conf, mpv shows the subtitles just fine.

**Comment by olivluca** [comment]
I got subtitles working with mpv android, see [](https://github.com/TheGlockMisc/mpv-android-argparse/issues/5#issuecomment-1226207237)

**Comment by justchokingaround** [comment]
closing this because i dropped android support in https://github.com/justchokingaround/lobster/commit/72b5752df1251d33c12a7f81627d1d20413be819, i recommend using cloudstream3 to watch movies/tv shows on android
