### ISSUE TITLE
question I dont know if this is a bug or what but previous search results are displayed?

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#130]
for example when you first search for trending movies lobster -t and then search for fast x by the time you search for a 3rd time the previous search results of lobster -t and fast x is included.

**Comment by ttx99** [comment]
I mean search results keep adding up by displaying the previous one

**Comment by justchokingaround** [comment]
probably a bug, i will check it later

**Comment by justchokingaround** [comment]
i cannot reproduce this. could you give me some exact steps that you did, that cause this behavior?

**Comment by ttx99** [comment]
you just need to search for a specific movie  quit the video search again  quit the video search again then you will notice that the search results becomes bigger from example 32/32 to 110/110

**Comment by ttx99** [comment]
btw does the script now work on windows?

**Comment by justchokingaround** [comment]
yes it does, i'll just need to edit the installation instructions in the readme. i'll let you know when that's done. i will try to replicate the bug later today then.

**Comment by justchokingaround** [comment]
@ttx99 i added the updated windows installation instructions to the README on the main branch, so you should now be able to install and use the script on windows. also for the bug described in the issue, i am unable to reproduce it. could you please update to the latest version, and if you still get the bug, either send me a screen recording or some logs, i can work with

**Comment by ttx99** [comment]
thanks seems fixed

**Comment by ttx99** [comment]
man can we also add select episode number just like in ani-cli?
