### ISSUE TITLE
support for mpvSockets module

### ISSUE THREAD

**Issue by CheesyChocolate** [justchokingaround/lobster#131]
**Is your feature request related to a problem? Please describe.**
There is a module called [mpvSocket](https://github.com/wis/mpvSockets). It creates one IPC socket per mpv instance, In hope to minimize broken pipe. the sockets are created inside the directory `/tmp/mpvSocket/` . If one uses this module, the lobster script can not find timestamp, since it looks for `/tmp/mpvsocket` but the actual socket is in `/tmp/mpvSocket/[PID]`  

**Describe the solution you'd like**
Optionally, if mpvSocket module is being used and directory `/tmp/mpvSocket/` is created, look for time stamp in `/tmp/mpvSocket/[PID]` 

**Describe alternatives you've considered**
lobster use a dedicated socket just for itself, so that it won't interfere with other sockets 

**Additional context**
my understanding of mpv, socat and sockets are limited. If I can do it myself, I make a PR.

**Comment by justchokingaround** [comment]
ok so there are 2 options here.

1. in the code of the current script, change `/tmp/mpvsocket` (i think that's what it's currently named, im not sure) into a variable, and let the user have the ability to customize it in the config file
2. this is more likely to happen. just work with the stderr mpv spits out and get the position from there. this would remove the socat dependency completely and would not require dealing with sockets again. in my testing so far this has also been more consistent with saving the position. i'll send an implementation i've already done in a diffsrent script, for this, in a second

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/jerry/blob/rewrite/jerry.sh#L537-L540

**Comment by CheesyChocolate** [comment]
I see

the method that you use in jerry script is going to work around this. great!!

tnx, your lobster script is amazing

**Comment by justchokingaround** [comment]
ty :) (i'll implement the changes later today or tomorrow then)

**Comment by justchokingaround** [comment]
done in c9a54e288d4c8ca3bcea368d15ad10145dad8d80 (currently only on the dev branch)

**Comment by CheesyChocolate** [comment]
wow, amazing

thank you (^_^)
