### ISSUE TITLE
can we have like replay episode

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#133]
select:
replay episode
next episode

**Comment by justchokingaround** [comment]
implemented in 3a643ddef2100b19607daf7793b8bced39a3eaa6 (on the dev branch)

**Comment by CheesyChocolate** [comment]
how about
```
next
replay
previous
select
change_quality
quit
```
I know it's to much to ask

**Comment by justchokingaround** [comment]
honestly it wouldn't be a problem to implement, i just don't really get the point, since select is already `Search`, quit is `Exit`, replay just got implemented. however i don't really see a point in change_quality (on the fly) and previous, as i've never had a point in my life where i used those options

**Comment by CheesyChocolate** [comment]
I agree with you, but
I use all these over ani-cli
select: there are time that I watched an old show partially, now I am quickly checking each episode to find where I left off
replay: for when I fell sleep, or leave and forget to pause and episode ends
previous: after a long time you get back to a show and want to check last episode, or want to set state episode to previous  
change_quality: for times someone uses a public wifi, so there's a need for lower quality

all these can be achieved manually, and In ones 80 years of life would save 30 min

Just a suggestion

**Comment by justchokingaround** [comment]
i will be implementing `change_quality`, however i don't deem `select` and `previous` worth implementing, since `Search` already exists, and it's only a few more clicks

**Comment by ttx99** [comment]
think of it like lobster is the ani-cli for movies/tv show. Thats why I asked for it I want it for be like ani-cli. but the decision is yours.

**Comment by justchokingaround** [comment]
i've maintained ani-cli for over a year, and i still don't like it's core philosophy. when i first wrote lobster, it practically didn't even have a selection menu at all. i don't think of this as worth implementing

**Comment by ttx99** [comment]
btw does hdrezka have english version?

**Comment by justchokingaround** [comment]
yes

**Comment by ttx99** [comment]
man can we also add select episode number just like in ani-cli?

**Comment by justchokingaround** [comment]
no, the `Search` option already covers that use case

**Comment by ttx99** [comment]
uuhm question, bro was fmovies just temporary fix for the outage or a planned provider? They kinda have a solid content library...

**Comment by justchokingaround** [comment]
planned provider

**Comment by ttx99** [comment]
Bro in windows i run this command 'ln -sf "$(scoop prefix mpv)/mpv.exe" /usr/bin/mpv' and mpv wont launch in ani-cli but lobster is fine [https://github.com/pystardust/ani-cli/issues/1181](url)

**Comment by ttx99** [comment]
https://vidsrc.me/ 
https://vidsrc.to/

**Comment by Kostrol** [comment]
> i will be implementing `change_quality`

I would be very happy if this was added. I got the idea to utilize lobster for my raspberry 3b for a simple setup. It struggles with 1080p content however, so being able to lower the video quality would solve that issue. So that's another example.

**Comment by justchokingaround** [comment]
i've recently started working on the rust rewrite of lobster, so sorry if im a bit inactive in the shell version development. if u'd like to PR this, feel free to do so, i'll review it in detail and help u out, but i don't have time/energy to implement this myself right now. iirc this fix is already implemented on the `hdrezka` branch, so you can check what i have done there

**Comment by ttx99** [comment]
lobster -x -t last voyage of demeter doesnt work
[lobster.log](https://github.com/justchokingaround/lobster/files/12482867/lobster.log)

**Comment by ttx99** [comment]
> i've recently started working on the rust rewrite of lobster, so sorry if im a bit inactive in the shell version development. if u'd like to PR this, feel free to do so, i'll review it in detail and help u out, but i don't have time/energy to implement this myself right now. iirc this fix is already implemented on the `hdrezka` branch, so you can check what i have done there

after rust will it be lobster LTS finally?

**Comment by justchokingaround** [comment]
yes, that's the idea

**Comment by ttx99** [comment]
doesnt work right now in linux and windows
[lobster.log](https://github.com/justchokingaround/lobster/files/12681297/lobster.log)

**Comment by ttx99** [comment]
windows has not been working for a while now
![2](https://github.com/justchokingaround/lobster/assets/95531944/c298bffd-a5ec-42f9-ab8c-d0ee284f7657)

**Comment by ttx99** [comment]
it works again in windows(according to my cousin) with the new update thx.

**Comment by ttx99** [comment]
@justchokingaround [https://github.com/junegunn/fzf/issues/3346](url)

**Comment by ttx99** [comment]
are we talking about replay for movies or just tv shows?

**Comment by ttx99** [comment]
btw the fzf bug still persist for tv shows only when pressing arrow key

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
