### ISSUE TITLE
Continue from history doesn't work (tac: command not found)

### ISSUE THREAD

**Issue by MickLib** [justchokingaround/lobster#134]
Whenever I try to continue from history (lobster -c) it gives me this error:

/opt/homebrew/bin/lobster: line 575: tac: command not found

**Comment by justchokingaround** [comment]
`brew install coreutils`

**Comment by MickLib** [comment]
Thanks. But now for some reason I get no entries when using -c despite the history working when manually selecting an episode.

Debug shows this:

+++ fzf --reverse --prompt 'Choose an entry:'
+++ cut -d '|' -f 1
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-w | -d delim] [file ...]

**Comment by MickLib** [comment]
Doesn't want to show for some reason. Probably the default macOS version. The coreutils one is version 9.3, the command is gcut. Maybe I can just replace cut with gcut in the script and it will work?

cut --version
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-w | -d delim] [file ...]

**Comment by justchokingaround** [comment]
it will work, however i'd prefer using posix cut, so i'll look into a fix for it later today

**Comment by MickLib** [comment]
Thank you.
This might be on me, because I am not running the latest macOS version (specifically 12.6.5), but knowing apple they tend to include pretty old utils either way.

**Comment by justchokingaround** [comment]
03d1bb10ba0bf141fed92314508e168de8d2572e should've fixed it (currently on the `dev` branch)
