### ISSUE TITLE
Subtitles when using downloading -d flag

### ISSUE THREAD

**Issue by sisyphus-kh** [justchokingaround/lobster#136]
When using the -d with -l for the subtitles it should download the subtitles along with the movie/tv show 

I've tried to add that feature but sometime it works and sometimes it doesn't, the problem appear to have something to do with having multiple subtitle links for one episode or movie 

![image](https://github.com/justchokingaround/lobster/assets/138269733/2381949d-f272-43d4-9c95-1424e23bc993)

I think when adding the -l flag & -d the script should  download the a subtitle file as the mp4 file

**Comment by justchokingaround** [comment]
this can be implemented, it would result in an ffmpeg that looks something like this:
```sh
ffmpeg -i input.mp4 -i english.vtt -i german.vtt \
-map 0:v -map 0:a -map 1 -map 2 \
-c:v copy -c:a copy -c:s srt \
-metadata:s:s:0 language=eng -metadata:s:s:1 language=ger \
output.mkv
```

the only issue at hand is parsing the subs etc to extract all of this information, as well as downloading each sub. i will look into implementing this. the resulting file would have in the `.mkv` format, since i don't think other formats can be used with embeded subtitles. it is up to the user to then convert the `.mkv` into a `.mp4`, there's a section for it in the wiki

**Comment by justchokingaround** [comment]
what should the behavior then be, if there are many subtitle tracks? you would download all of them to the current directory? if i implement everything programmatically, you end up with one `.mkv` file that contains subs inside of it, which can toggled on/off

**Comment by sisyphus-kh** [comment]
I guess I haven't thought that there would be many subtitle tracks, embedding makes more sense now. the above code just download the first subtitle track if there two English ones for example

**Comment by medanisjbara** [comment]
@justchokingaround How do you intend to do the parsing for the subs ? for vtt I don't see anything in the file we can parse using regex which can determine the language. Here's an [example](https://cc.2cdns.com/3c/9b/3c9bc33151ea66a182bf8e38f5c01491/3c9bc33151ea66a182bf8e38f5c01491.vtt) where both the filename and the content give no indication that the subs are english.

Note that (for now) [my current approach](https://github.com/medanisjbara/lobster/blob/v4.3/lobster.sh#L594) is to label them all as `unknown`. Let me know if you have something else in mind.

**Comment by medanisjbara** [comment]
Btw, I can set it to be the `basename` of the file name (without extension) if that's okay (a lot of files are named in a good way .. so IMO that's the best we can do)

**Comment by justchokingaround** [comment]
> @justchokingaround How do you intend to do the parsing for the subs ? for vtt I don't see anything in the file we can parse using regex which can determine the language. Here's an [example](https://cc.2cdns.com/3c/9b/3c9bc33151ea66a182bf8e38f5c01491/3c9bc33151ea66a182bf8e38f5c01491.vtt) where both the filename and the content give no indication that the subs are english.
> 
> Note that (for now) [my current approach](https://github.com/medanisjbara/lobster/blob/v4.3/lobster.sh?rgh-link-date=2024-07-26T15%3A46%3A59Z#L594) is to label them all as `unknown`. Let me know if you have something else in mind.

this is usually specified in the json label keys
![image](https://github.com/user-attachments/assets/e70c747f-6c82-4fc2-9e50-4d6accd48e53)

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
