### ISSUE TITLE
 lobster - t search results are diferrent without ueberzugpp 

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#137]
Pls make it so that non ueberzugpp users have the same search results. Basically lobster -t only displays movies while lobster -t -i displays movies and tv shows which should be the default behavior.

**Comment by ttx99** [comment]
![1](https://github.com/justchokingaround/lobster/assets/95531944/1eeede21-2ea5-4522-92d6-e9ff7de79600)
![2](https://github.com/justchokingaround/lobster/assets/95531944/e5b9194d-6c55-450a-98f8-7db8b324e8e8)

**Comment by justchokingaround** [comment]
i'll look into fixing it on the dev branch later

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
