### ISSUE TITLE
Media player not opening on Windows

### ISSUE THREAD

**Issue by Bancsis** [justchokingaround/lobster#138]
**Describe the bug**
I've tried re-installing several times and there's no issues or errors in the process, however, when I run lobster and select a movie nothing happens. I have it working fine on my Mac and ordinarily it would open the media player. I've checked that MPV is in pathed correctly in the windows environment variables. 

**To Reproduce**
1. Install Lobster through windows setup process in readme
2. Type 'lobster avatar'
3. Select the first option

**Expected behavior**
MPV to display with the movie

**Screenshots**
![image](https://github.com/justchokingaround/lobster/assets/56519024/8731dfca-6566-473d-8b72-39a9fbd1d401)
Nothing happens
![image](https://github.com/justchokingaround/lobster/assets/56519024/fd275340-c502-4771-b242-233b157bcbe0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: 
 - Version 22H2

**Comment by justchokingaround** [comment]
could you run `lobster avatar -x` and send me the logs found at `/tmp/lobster.log` please?

**Comment by Bancsis** [comment]
+ debug=1
+ shift
+ '[' 0 -gt 0 ']'
++ printf %s ' avatar'
++ tr ' ' -
++ sed 's/^-//g'
+ query=avatar
+ '[' 0 = 1 ']'
+ '[' -z UpCloud ']'
+ '[' '' = 1 ']'
+ '[' '' = movie ']'
+ '[' '' = tv ']'
+ main
+ '[' -z '' ']'
+ '[' -z avatar ']'
+ search avatar
+ '[' 0 = 1 ']'
++ curl -s https://flixhq.to/search/avatar
++ sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g'
++ sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p'
++ tee /dev/null
+ response='Avatar (movie) [2009]	19690
The Last Avatar (movie) [2014]	65453
The King&#39;s Avatar (tv) [EPS 40]	49377
Avatar: The Last Airbender (tv) [EPS 21]	38893
Avatar: The Way of Water (movie) [2022]	79936'
+ '[' -z 'Avatar (movie) [2009]	19690
The Last Avatar (movie) [2014]	65453
The King&#39;s Avatar (tv) [EPS 40]	49377
Avatar: The Last Airbender (tv) [EPS 21]	38893
Avatar: The Way of Water (movie) [2022]	79936' ']'
+ '[' -z 'Avatar (movie) [2009]	19690
The Last Avatar (movie) [2014]	65453
The King&#39;s Avatar (tv) [EPS 40]	49377
Avatar: The Last Airbender (tv) [EPS 21]	38893
Avatar: The Way of Water (movie) [2022]	79936' ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 0 ']'
++ printf %s 'Avatar (movie) [2009]	19690
The Last Avatar (movie) [2014]	65453
The King&#39;s Avatar (tv) [EPS 40]	49377
Avatar: The Last Airbender (tv) [EPS 21]	38893
Avatar: The Way of Water (movie) [2022]	79936'
++ fzf --reverse --with-nth 1 -d '\t' --header 'Choose a Movie or TV Show'
+ choice='Avatar (movie) [2009]	19690'
++ printf %s 'Avatar (movie) [2009]	19690'
++ sed -nE 's@(.*) \((movie|tv)\).*@\1@p'
+ title=Avatar
++ printf %s 'Avatar (movie) [2009]	19690'
++ sed -nE 's@(.*) \((movie|tv)\).*@\2@p'
+ media_type=movie
++ printf %s 'Avatar (movie) [2009]	19690'
++ cut -f2
+ media_id=19690
+ '[' movie = tv ']'
+ keep_running=true
+ loop
+ '[' true = true ']'
+ get_embed
+ '[' movie = movie ']'
++ curl -s https://flixhq.to/ajax/movie/episodes/19690
++ tr -d '\n'
++ sed -nE 's_.*href="([^"]*)".*UpCloud.*_\1_p'
+ movie_page=https://flixhq.to/watch-movie/watch-avatar-19690.5297449
++ printf %s https://flixhq.to/watch-movie/watch-avatar-19690.5297449
++ sed -nE 's_.*-([0-9]*)\.([0-9]*)$_\2_p'
+ episode_id=5297449
++ curl -s https://flixhq.to/ajax/sources/5297449
++ sed -nE 's_.*"link":"([^"]*)".*_\1_p'
+ embed_link='https://dokicloud.one/embed-4/kod0hAjvx3fQ?z='
+ '[' -z 'https://dokicloud.one/embed-4/kod0hAjvx3fQ?z=' ']'
+ '[' -z 'https://dokicloud.one/embed-4/kod0hAjvx3fQ?z=' ']'
+ get_json
++ printf %s 'https://dokicloud.one/embed-4/kod0hAjvx3fQ?z='
++ sed -nE 's_(.*)/embed-(4|6)/(.*)\?z=$_\1\t\2\t\3_p'
+ parse_embed='https://dokicloud.one	4	kod0hAjvx3fQ'
++ printf %s 'https://dokicloud.one	4	kod0hAjvx3fQ'
++ cut -f1
+ provider_link=https://dokicloud.one
++ printf %s 'https://dokicloud.one	4	kod0hAjvx3fQ'
++ cut -f3
+ source_id=kod0hAjvx3fQ
++ printf %s 'https://dokicloud.one	4	kod0hAjvx3fQ'
++ cut -f2
+ embed_type=4
++ curl -s 'https://dokicloud.one/ajax/embed-4/getSources?id=kod0hAjvx3fQ' -H 'X-Requested-With: XMLHttpRequest'
+ json_data='{"sources":"U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}'
+ '[' -n '{"sources":"U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}' ']'
+ extract_from_json
++ printf %s '{"sources":"U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}'
++ tr '{}' '\n'
++ sed -nE 's_.*"file":"([^"]*)".*_\1_p'
++ grep '\.m3u8'
+ encrypted=
+ '[' -n '' ']'
++ curl -s https://github.com/enimax-anime/key/blob/e4/key.txt
++ sed -nE 's_.*js-file-line">(.*)<.*_\1_p'
+ key=
++ printf %s '{"sources":"U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}'
++ tr '{|}' '\n'
++ sed -nE 's_.*"sources":"([^"]*)".*_\1_p'
++ head -1
+ encrypted_video_link=U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG
++ printf %s U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG
++ base64 -d
++ openssl enc -aes-256-cbc -d -md md5 -k ''
++ sed -nE 's_.*"file":"([^"]*)".*_\1_p'
+ video_link=
++ printf %s '{"sources":"U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}'
++ sed -e 's|U2FsdGVkX1+ItATzoO+A7YwMSao5qs33CWZbBvvsvJH6GXB4GnHS4+PEOsMxGNTh7sfJoBseF5fCxQw7D9j3q66p9Y7YkyQjWx4U+zD6DyHYqWAfYS4ISwbX3rnmpn+bSt21053u++fEG8vXOEf3dsWetik7SOd+0gq3T20DAN+CiQAVppgKj85KwZ0GNN6ruG603bwPcsbJKwzIpfq0DByy89dybohbbPuSov8FnQpejiCVhHfd8CWHxUi0eBEtpuNc878EfV0Dyv5mazhMsWnIs5Irk8GaFAL24sInwLlFU/LI578YQjqlbKPBU+UlST7CoVRVZDga6GeuOrspNPuubVLbEl+5MCYgwUGo6Fd5kfjUOWCsOU9n87A9jrkHkJb05uQ2usPaWRzLLSxX1VUgYb+M8KT3ghYV8RjpWdEZ0GG7WmE5ouftbszDzJbdYf16TOfba5iCcSVSX0SGt8PrQq+XYspttUgGKdf8rh5d0nJHC2kZDZmfZagXBIDG||'
+ json_data='{"sources":"","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}'
+ '[' -n '' ']'
+ '[' 0 = 1 ']'
++ printf %s '{"sources":"","tracks":[{"file":"https://cc.2cdns.com/34/21/34219aedb8012ef6f18392fdf9ea1b0d/34219aedb8012ef6f18392fdf9ea1b0d.vtt","label":"Arabic","kind":"captions"},{"file":"https://cc.2cdns.com/41/e8/41e8cb8eb6a701f59d5924cca036cbf1/41e8cb8eb6a701f59d5924cca036cbf1.vtt","label":"Croatian","kind":"captions"},{"file":"https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt","label":"English","kind":"captions","default":true},{"file":"https://cc.2cdns.com/5e/ce/5ecefeaa31fa079e8bf08ff0856260a5/5ecefeaa31fa079e8bf08ff0856260a5.vtt","label":"Spanish","kind":"captions"},{"file":"https://prev.2cdns.com/_m_preview/c4/c4afdbe252c5346962050145ae2fbbff/thumbnails/sprite.vtt","kind":"thumbnails"}],"server":29}'
++ tr '{}' '\n'
++ sed -nE 's@"file":"([^"]*)","label":"(.nglish)[,"\ ].*@\1@p'
+ subs_links=https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt
+ subs_arg=--sub-file
++ printf %s https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt
++ wc -l
+ num_subs=0
+ '[' 0 -gt 0 ']'
+ '[' -z https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt ']'
+ '[' -z '' ']'
+ exit 1

**Comment by Bancsis** [comment]
[lobster.log](https://github.com/justchokingaround/lobster/files/11972177/lobster.log)

**Comment by justchokingaround** [comment]
fixed it in https://github.com/justchokingaround/lobster/commit/0768d91e2417a6b9819c4b440f066599fc399c19 on the dev branch. this was a problem specific to that movie source. i will merge it into main when i finish implementing a few other things, it should take about 3-4 days. 

also flixhq just went down temporarily (i hope), so can't rly test if it works :(

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/45b0ce93468ead21ea5e60afafe13348d170ac22 should fix it, now merged in `main`. you can just update the script with `lobster -u`

**Comment by Bancsis** [comment]
So it's "loading" it now, but MPV isn't displaying. I've tried `scoop uninstall mpv` and reinstalling it but no luck. Environment variables are setup:
![image](https://github.com/justchokingaround/lobster/assets/56519024/b05152e3-ca09-4563-8790-ab22d0271949)
![image](https://github.com/justchokingaround/lobster/assets/56519024/9252a320-85a0-48d6-b12c-181e3489cd51)

**Comment by justchokingaround** [comment]
i'll need the logs again please

**Comment by Bancsis** [comment]
No problem
[lobster.log](https://github.com/justchokingaround/lobster/files/11973121/lobster.log)

**Comment by justchokingaround** [comment]
this command does not work for you:
```sh
mpv --sub-file=https://cc.2cdns.com/96/61/96610672cb2b51dd9633b36698b67b5f/96610672cb2b51dd9633b36698b67b5f.vtt --force-media-title=Avatar "https://eerht.artdesigncdn.net/_v10/d6291898b609b71e68f4633273d2754f12b90e18f1c4e224519264b46624d78fcc84da4046fe720fa9922037b2fb615649fec4cd2a79a75295740ad5a89e5b871d7204c5a07583f56913af6439351b86c3bdee6516be59a35ac7534376f3f39fc47d71405e8d156a479e4608b88937e90403848357fa389e0f6f25a60e1d766039cde2d1a354725fab454beb37be0124/playlist.m3u8"
```

it's a problem with your mpv. i suggest doing a
```sh
rm $(which mpv)
```
and then symlinking by running the following command:
```sh
sudo ln -sf <path to the binary in your scoop apps directory> /usr/bin/mpv
```

**Comment by justchokingaround** [comment]
i think the default executable is mpv.exe or something like that, im not sure

**Comment by Bancsis** [comment]
Okay that wasn't working for me but I did manage to resolve it differently. I did `scoop install mpv` and then `ln -sf "$(scoop prefix mpv)/mpv.exe" /usr/bin/mpv` in git bash. I can now load Avatar at the very least :D Thank you!

**Comment by justchokingaround** [comment]
great! well done
