### ISSUE TITLE
the script just dont work when selecting tv episode number as soon as you press down arrow key in Windows 10

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#139]
launch in windows terminal using gitbash> lobster > skinwalker ranch > season 4 > when I press the down arrow key to select the last episode the script sort of like exit or goes blank.

OS Windows 10

**Comment by ttx99** [comment]
also ani-cli can be launch with powershell and lobster cant

**Comment by justchokingaround** [comment]
are you on the latest version? can you send me some logs please?

**Comment by ttx99** [comment]
i reinstalled windows 10 and now its saying i dont have mpv installed weird cause i install ani-cli first.

**Comment by justchokingaround** [comment]
refer to this:
https://github.com/justchokingaround/lobster/issues/138#issuecomment-1624436351

**Comment by ttx99** [comment]
Do i need to do scoop install git?

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/issues/138#issuecomment-1624160227

**Comment by ttx99** [comment]
yes, I cant send logs cause if I press down arrow the script just exit 

I typed this lobster skinwalker -x > Season 1 > then as soon as i press the down arrow key the script just exits

user@DESKTOP-84JQO8R MINGW64 ~
$ lobster skinwalker -x
+ debug=1
+ shift
+ '[' 0 -gt 0 ']'
++ printf %s ' skinwalker'
++ tr ' ' -
++ sed 's/^-//g'
+ query=skinwalker
+ '[' 0 = 1 ']'
+ '[' -z UpCloud ']'
+ '[' '' = 1 ']'
+ '[' '' = movie ']'
+ '[' '' = tv ']'
+ main
+ '[' -z '' ']'
+ '[' -z skinwalker ']'
+ search skinwalker
+ '[' 0 = 1 ']'
++ curl -s https://flixhq.to/search/skinwalker
++ sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g'
++ sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p'
+ tmp_ep_id=
+ '[' -z '' ']'
+ exit 1

**Comment by justchokingaround** [comment]
does this command work for you?
```sh
curl -s "https://flixhq.to/search/skinwalker" | sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g' | sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p' | tee /dev/null
```

**Comment by ttx99** [comment]
$ curl -s "https://flixhq.to/search/skinwalker" | sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g' | sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p' | tee /dev/null
Skinwalker (movie) [2021]       70711
Skinwalker Ranch (movie) [2013] 1203
Beyond Skinwalker Ranch (tv) [EPS 4]    97354
Hunt for the Skinwalker (movie) [2018]  15261
The Secret of Skinwalker Ranch (tv) [EPS 10]    70648
Skinwalkers (movie) [2006]      11871

**Comment by ttx99** [comment]
when Im about to select a specific episode number and i press the down arrow key the script exits.

**Comment by justchokingaround** [comment]
i'll need some more verbose logs in this case:
```sh
sh -x $(which lobster) skinwalker | tee /tmp/verbose.log
```

log is in `/tmp/verbose.log`

**Comment by justchokingaround** [comment]
afaik, you can just do `cat /tmp/verbose.log | clip` and it will copy to the clipboard

**Comment by ttx99** [comment]
+ applications=/c/Users/user/.local/share/applications/lobster
+ images_cache_dir=/tmp/lobster/lobster-images
+ tmp_position=/tmp/lobster_position
+ case "$(uname -s)" in
++ uname -s
+ separator=';'
+ path_thing=
+ sed=sed
+ command -v notify-send
+ notify=false
+ command -v hxunent
+ hxunent='tee /dev/null'
+ dep_ch grep sed curl fzf mpv
+ for dep in "$@"
+ command -v grep
+ command -v grep
+ for dep in "$@"
+ command -v sed
+ command -v sed
+ for dep in "$@"
+ command -v curl
+ command -v curl
+ for dep in "$@"
+ command -v fzf
+ command -v fzf
+ for dep in "$@"
+ command -v mpv
+ command -v mpv
+ '[' '' = 1 ']'
+ configuration
+ '[' -n '' ']'
+ config_dir=/c/Users/user/.config/lobster
+ '[' -n '' ']'
+ data_dir=/c/Users/user/.local/share/lobster
+ '[' '!' -d /c/Users/user/.config/lobster ']'
+ '[' '!' -d /c/Users/user/.local/share/lobster ']'
+ '[' -f /c/Users/user/.config/lobster/lobster_config.txt ']'
+ '[' -z '' ']'
+ base=flixhq.to
+ '[' -z '' ']'
+ player=mpv
+ '[' -z '' ']'
+ download_dir=/c/Users/user
+ '[' -z '' ']'
+ provider=UpCloud
+ '[' -z '' ']'
+ history=0
+ '[' -z '' ']'
+ subs_language=english
++ printf %s english
++ cut -c2-
+ subs_language=nglish
+ '[' -z '' ']'
+ histfile=/c/Users/user/.local/share/lobster/lobster_history.txt
++ dirname /c/Users/user/.local/share/lobster/lobster_history.txt
+ mkdir -p /c/Users/user/.local/share/lobster
+ '[' -z '' ']'
+ use_external_menu=0
+ '[' -z '' ']'
+ image_preview=0
+ '[' -z '' ']'
+ debug=0
+ '[' -z '' ']'
+ preview_window_size=up:60%:wrap
+ '[' -z '' ']'
+ ueberzug_x=10
+ '[' -z '' ']'
+ ueberzug_y=3
+ '[' -z '' ']'
++ tput lines
+ ueberzug_max_width=15
+ '[' -z '' ']'
++ tput lines
+ ueberzug_max_height=15
+ '[' -z '' ']'
+ remove_tmp_lobster=1
+ '[' -z '' ']'
+ json_output=0
+ '[' 0 = 1 ']'
+ query=
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ '[' skinwalker '!=' skinwalker ']'
+ query=' skinwalker'
+ shift
+ '[' 0 -gt 0 ']'
++ printf %s ' skinwalker'
++ tr ' ' -
++ sed 's/^-//g'
+ query=skinwalker
+ '[' 0 = 1 ']'
+ '[' -z UpCloud ']'
+ '[' '' = 1 ']'
+ '[' '' = movie ']'
+ '[' '' = tv ']'
+ main
+ '[' -z '' ']'
+ '[' -z skinwalker ']'
+ search skinwalker
+ '[' 0 = 1 ']'
++ curl -s https://flixhq.to/search/skinwalker
++ sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g'
++ sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p'
++ tee /dev/null
+ response='Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871'
+ '[' -z 'Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871' ']'
+ '[' -z 'Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871' ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 0 ']'
++ printf %s 'Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871'
++ fzf --reverse --with-nth 1 -d '\t' --header 'Choose a Movie or TV Show'
+ choice='Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ printf %s 'Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ sed -nE 's@(.*) \((movie|tv)\).*@\1@p'
+ title='Beyond Skinwalker Ranch'
++ printf %s 'Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ sed -nE 's@(.*) \((movie|tv)\).*@\2@p'
+ media_type=tv
++ printf %s 'Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ cut -f2
+ media_id=97354
+ '[' tv = tv ']'
+ choose_episode
+ '[' -z '' ']'
++ curl -s https://flixhq.to/ajax/v2/tv/seasons/97354
++ sed -nE 's@.*href=".*-([0-9]*)">(.*)</a>@\2\t\1@p'
++ launcher 'Select a season: ' 1
++ case "$use_external_menu" in
++ '[' -z 1 ']'
++ '[' -n 1 ']'
++ fzf --reverse --prompt 'Select a season: ' --with-nth 1 -d '\t'
+ tmp_season_id='Season 1	76354'
+ '[' -z 'Season 1	76354' ']'
++ printf %s 'Season 1	76354'
++ cut -f1
+ season_title='Season 1'
++ printf %s 'Season 1	76354'
++ cut -f2
+ season_id=76354
++ curl -s https://flixhq.to/ajax/v2/season/episodes/76354
++ sed ':a;N;$!ba;s/\n//g;s/class="nav-item"/\n/g'
++ sed -nE 's@.*data-id="([0-9]*)".*title="([^"]*)">.*@\2\t\1@p'
++ tee /dev/null
++ launcher 'Select an episode: ' 1
++ case "$use_external_menu" in
++ '[' -z 1 ']'
++ '[' -n 1 ']'
++ fzf --reverse --prompt 'Select an episode: ' --with-nth 1 -d '\t'
+ tmp_ep_id=
+ '[' -z '' ']'
+ exit 1

**Comment by ttx99** [comment]
this is when i press down arrow key to select episode 4 

+ applications=/c/Users/user/.local/share/applications/lobster
+ images_cache_dir=/tmp/lobster/lobster-images
+ tmp_position=/tmp/lobster_position
+ case "$(uname -s)" in
++ uname -s
+ separator=';'
+ path_thing=
+ sed=sed
+ command -v notify-send
+ notify=false
+ command -v hxunent
+ hxunent='tee /dev/null'
+ dep_ch grep sed curl fzf mpv
+ for dep in "$@"
+ command -v grep
+ command -v grep
+ for dep in "$@"
+ command -v sed
+ command -v sed
+ for dep in "$@"
+ command -v curl
+ command -v curl
+ for dep in "$@"
+ command -v fzf
+ command -v fzf
+ for dep in "$@"
+ command -v mpv
+ command -v mpv
+ '[' '' = 1 ']'
+ configuration
+ '[' -n '' ']'
+ config_dir=/c/Users/user/.config/lobster
+ '[' -n '' ']'
+ data_dir=/c/Users/user/.local/share/lobster
+ '[' '!' -d /c/Users/user/.config/lobster ']'
+ '[' '!' -d /c/Users/user/.local/share/lobster ']'
+ '[' -f /c/Users/user/.config/lobster/lobster_config.txt ']'
+ '[' -z '' ']'
+ base=flixhq.to
+ '[' -z '' ']'
+ player=mpv
+ '[' -z '' ']'
+ download_dir=/c/Users/user
+ '[' -z '' ']'
+ provider=UpCloud
+ '[' -z '' ']'
+ history=0
+ '[' -z '' ']'
+ subs_language=english
++ printf %s english
++ cut -c2-
+ subs_language=nglish
+ '[' -z '' ']'
+ histfile=/c/Users/user/.local/share/lobster/lobster_history.txt
++ dirname /c/Users/user/.local/share/lobster/lobster_history.txt
+ mkdir -p /c/Users/user/.local/share/lobster
+ '[' -z '' ']'
+ use_external_menu=0
+ '[' -z '' ']'
+ image_preview=0
+ '[' -z '' ']'
+ debug=0
+ '[' -z '' ']'
+ preview_window_size=up:60%:wrap
+ '[' -z '' ']'
+ ueberzug_x=10
+ '[' -z '' ']'
+ ueberzug_y=3
+ '[' -z '' ']'
++ tput lines
+ ueberzug_max_width=15
+ '[' -z '' ']'
++ tput lines
+ ueberzug_max_height=15
+ '[' -z '' ']'
+ remove_tmp_lobster=1
+ '[' -z '' ']'
+ json_output=0
+ '[' 0 = 1 ']'
+ query=
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ '[' skinwalker '!=' skinwalker ']'
+ query=' skinwalker'
+ shift
+ '[' 0 -gt 0 ']'
++ printf %s ' skinwalker'
++ tr ' ' -
++ sed 's/^-//g'
+ query=skinwalker
+ '[' 0 = 1 ']'
+ '[' -z UpCloud ']'
+ '[' '' = 1 ']'
+ '[' '' = movie ']'
+ '[' '' = tv ']'
+ main
+ '[' -z '' ']'
+ '[' -z skinwalker ']'
+ search skinwalker
+ '[' 0 = 1 ']'
++ curl -s https://flixhq.to/search/skinwalker
++ sed ':a;N;$!ba;s/\n//g;s/class="flw-item"/\n/g'
++ sed -nE 's@.*<a href=".*/(tv|movie)/watch-.*-([0-9]*)".*title="([^"]*)".*class="fdi-item">([^<]*)</span>.*@\3 (\1) [\4]\t\2@p'
++ tee /dev/null
+ response='Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871'
+ '[' -z 'Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871' ']'
+ '[' -z 'Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871' ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 1 ']'
+ '[' 0 = 0 ']'
++ printf %s 'Skinwalker (movie) [2021]	70711
Skinwalker Ranch (movie) [2013]	1203
Beyond Skinwalker Ranch (tv) [EPS 4]	97354
Hunt for the Skinwalker (movie) [2018]	15261
The Secret of Skinwalker Ranch (tv) [EPS 10]	70648
Skinwalkers (movie) [2006]	11871'
++ fzf --reverse --with-nth 1 -d '\t' --header 'Choose a Movie or TV Show'
+ choice='Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ printf %s 'Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ sed -nE 's@(.*) \((movie|tv)\).*@\1@p'
+ title='Beyond Skinwalker Ranch'
++ printf %s 'Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ sed -nE 's@(.*) \((movie|tv)\).*@\2@p'
+ media_type=tv
++ printf %s 'Beyond Skinwalker Ranch (tv) [EPS 4]	97354'
++ cut -f2
+ media_id=97354
+ '[' tv = tv ']'
+ choose_episode
+ '[' -z '' ']'
++ curl -s https://flixhq.to/ajax/v2/tv/seasons/97354
++ sed -nE 's@.*href=".*-([0-9]*)">(.*)</a>@\2\t\1@p'
++ launcher 'Select a season: ' 1
++ case "$use_external_menu" in
++ '[' -z 1 ']'
++ '[' -n 1 ']'
++ fzf --reverse --prompt 'Select a season: ' --with-nth 1 -d '\t'
+ tmp_season_id='Season 1	76354'
+ '[' -z 'Season 1	76354' ']'
++ printf %s 'Season 1	76354'
++ cut -f1
+ season_title='Season 1'
++ printf %s 'Season 1	76354'
++ cut -f2
+ season_id=76354
++ curl -s https://flixhq.to/ajax/v2/season/episodes/76354
++ sed ':a;N;$!ba;s/\n//g;s/class="nav-item"/\n/g'
++ sed -nE 's@.*data-id="([0-9]*)".*title="([^"]*)">.*@\2\t\1@p'
++ tee /dev/null
++ launcher 'Select an episode: ' 1
++ case "$use_external_menu" in
++ '[' -z 1 ']'
++ '[' -n 1 ']'
++ fzf --reverse --prompt 'Select an episode: ' --with-nth 1 -d '\t'
+ tmp_ep_id=
+ '[' -z '' ']'
+ exit 1

**Comment by justchokingaround** [comment]
might be an fzf issue in that case, i will check it on windows later today

**Comment by ttx99** [comment]
should I install  wezterm through scoop?

**Comment by justchokingaround** [comment]
this is a bug upstream, with fzf, nothing i can do to fix it:
https://github.com/junegunn/fzf/issues/3346

for now you can use ctrl+j and ctrl+k to go down and up, which is what i've always done as it's more ergonomic
