### ISSUE TITLE
sflix.se is the best to scrape

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#14]
Sflix.se uploads content faster than himovies.  She-hulk was already up earlier.

In the script with himovies
![1](https://user-images.githubusercontent.com/95531944/186628821-4250cd0a-c2d6-4d46-bb09-2d31c109cd91.png)

example vidcloud link was already up in sflix.se
![2](https://user-images.githubusercontent.com/95531944/186628968-4e260f0d-5701-4f60-82c4-0bc18337ca42.png)

but it's fine if you don't want to it's just a suggestion

**Comment by justchokingaround** [comment]
sflix is a mirror of himovies, and it uses the same providers (Upcloud, Vidcloud...)
this looks like a bug withing the lobster script itself (my intention was to use Upcloud as default, and fall back to Vidcloud if no links were found, but looks like it didn't work)
i'll try fixing it or adding the option to be able to set ur preferred provider in the config file
atm i have a ton of work and no computer i can use so i can't give an ETA just yet :(

**Comment by ttx99** [comment]
well that explains it.  It's okay dude thx for for this script dude


this if from himovies 
![1](https://user-images.githubusercontent.com/95531944/186682472-7fc94953-c897-4ed7-8a4b-1e6ec5130345.png)

**Comment by ttx99** [comment]
If you go for the config way, can you also make a config for video resolution?

**Comment by justchokingaround** [comment]
sure, i'll implement all of this once i get a computer on my habds (hopefully soon)

**Comment by justchokingaround** [comment]
fixed in 32841b4d710a5e6d85ecbe3ccb699e8ddb9e97be
