### ISSUE TITLE
aur PKGBUILD fix

### ISSUE THREAD

**Issue by CheesyChocolate** [justchokingaround/lobster#141]
please check this [comment](https://aur.archlinux.org/packages/lobster-git#comment-923155) at arch aur.
the proposed change is crucial to correct functionality of aur helpers.   

if further explanation needed, I can provide.

**Comment by justchokingaround** [comment]
yes, thank you for the reminder. i am a bit overwhelmed with uni work atm, hence why i've been putting it off for quite some time. would you mind maintaining the aur package, i can give you the permissions needed. it's fine if u don't want to, for any reason, i don't mind, i'll just do it in a few days?

**Comment by CheesyChocolate** [comment]
I would be happy to help, If you want I can co maintain AUR PKGBUILD. also since this is a git PKGBUILD, this change hopefully will be the last change in PKGBUILD.  
there is no urgency in this manner.

**Comment by justchokingaround** [comment]
great to hear! just let me know what your aur username is, and how i should do the tagging with git please

**Comment by CheesyChocolate** [comment]
here is my username [Lemon](https://aur.archlinux.org/account/Lemon)
there is no need to bump package version for a git package. an aur helper with 'devel' flag will check for new version. 
change the `pkgver` to ( current sed will cause aur helper to be confused which is newer version `4.0.1` or `v4.0.6`)
```
git describe --long --tags --abbrev=7 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
```
then you will be free to tag the git repo however you want.

**Comment by justchokingaround** [comment]
i added you as co-maintainer for the `-git` package and ask the original maintainer to add you as a co-maintainer for the regular package. i'd be very grateful if you would fix the PKGBUILDs, i'm currently a bit overwhelmed with uni work and i would prefer not having to worry about maintaining the lobster packages

if my understanding is correct, after your changes, this is the command i'd have to run on every push i make to `main`:
```sh
git tag -a "v4.0.3" -m "bump version to v4.0.3"
```

i'm new to git tags

**Comment by CheesyChocolate** [comment]
I will maintain AUR PKGBUILD.

currently you are free to tag weather you do or not, users will get update in every push. (so no need to tag for every push) since version has revision number (ie. 4.0.0.r19.g7bbd799-1). 

you can change the PKGBUILD so the version has no revision (ie. 4.0.6) and as such  users get update every tag increment. I will purpose this change once the script is more stable and you don't want to introduce breaking changes between tags.

**Comment by justchokingaround** [comment]
great! i think i understood what you mean, so i won't be tagging for now, and when it becomes more stable, i will do tags for commits that introduce "bigger" changes

**Comment by justchokingaround** [comment]
thanks again!
