### ISSUE TITLE
history shows wrong title.

### ISSUE THREAD

**Issue by on-ii** [justchokingaround/lobster#143]
**Describe the bug**
lobster shows wrong title for shows on history while episodes/seasons remain fine.

instead of showing the bear in the title, lobster -c shows breaking bad which i've previously watched

**Screenshots**
![image](https://github.com/justchokingaround/lobster/assets/95423136/518146f9-741b-4f87-9d88-c5694d146713)

**Desktop**
 - OS: Manjaro 6.3.12-1
 - Lobster Version: 4.0.7

**Comment by justchokingaround** [comment]
what are the steps to reproduce this please?

**Comment by on-ii** [comment]
> what are the steps to reproduce this please?
1. search breaking bad.
2. finished the episode [season 5; episode 10]
3. exit
4. now searched the bear 
5. finished the episode and exited [season 2; episode 5]
6. lobster -c

now the title shows "1|Breaking bad|season 2|Eps:5" which was the episode of "the bear"
continuing plays the bear.

**Comment by justchokingaround** [comment]
i'll check why that happens

**Comment by on-ii** [comment]
the issue seems to have resolved itself. forgot to close the ticket. apologies.
