### ISSUE TITLE
script doesnt work

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#144]
lobster -t -x
[lobster.log](https://github.com/justchokingaround/lobster/files/12091479/lobster.log)

lobster -x the flash
[lobster.log](https://github.com/justchokingaround/lobster/files/12091497/lobster.log)

[lobster.log](https://github.com/justchokingaround/lobster/files/12091650/lobster.log)

**Comment by justchokingaround** [comment]
looking into it

**Comment by ttx99** [comment]
okay its weird sometimes it works now hmmm
[lobster.log](https://github.com/justchokingaround/lobster/files/12091758/lobster.log)

**Comment by justchokingaround** [comment]
i added a new provider in https://github.com/justchokingaround/lobster/commit/06a173e46629343c8683e04423e5101294f22f30 on the dev branch, fmovies, which is actually really good. right now i only implemented movies, without any history features or anything, it only plays movies and that's it. you can use it as a temporary fix for the moment, with:
```sh
sh <(curl -s https://raw.githubusercontent.com/justchokingaround/lobster/dev/lobster.sh) -w fmovies the flash
```

**Comment by justchokingaround** [comment]
(speaking of which, i think i'm gonna watch that movie now)

**Comment by ttx99** [comment]
now, multiple providers makes sense thanks bro

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/dfaf1a3a93f6793127c7cbea20759ef7333a662c should fix this

**Comment by ttx99** [comment]
thanks bro fixed..
