### ISSUE TITLE
Lobster stopped working

### ISSUE THREAD

**Issue by aylinturgut0** [justchokingaround/lobster#15]
**Lobster stopped working**
I typed in lobster on mac terminal and searched for multiple shows. Always got 0 results. It was working fine a few hours ago.

**Expected behavior**
Open terminal, type in lobster, type a movie name, get 0 results

**Screenshot**

<img width="582" alt="Screen Shot 2022-08-26 at 00 01 02" src="https://user-images.githubusercontent.com/108519489/186768098-24fa7d28-5255-462e-aedb-7bdb7e6c9ab9.png">

**Desktop**
 - OS: Mac OS
 - Browser: Safari
 - Version 12.5 
 - m1 (idk if relevant)

**Comment by justchokingaround** [comment]
the website's search engine is down. will have to wait some time, then if it's still broken i'll prolly switch to scraping a mirror

**Comment by aylinturgut0** [comment]
oh, should I delete this issue?

**Comment by justchokingaround** [comment]
nope, since the website is broken rn
