### ISSUE TITLE
error - no results found even after finding not working

### ISSUE THREAD

**Issue by Loskoss** [justchokingaround/lobster#153]
**Describe the bug**
Cannot find the results and if manages to find the results only displays some of them .
Errors i get are error - no results found and just error after selection a movie(rare case)

- I don't know if its reproducible 

1. just install the lobster-git
2. run lobster <query>
3 . See error

**Expected behavior**
The screen shown on the preview should appear but error no results is shown , and by mistake if its find results it only shows 4 or 5 results and the images are all over the place.

**Desktop :**
 - OS: Arch Linux
 - Linux Zen kernel : 6.4.10-zen2-1-zen
 - Version  4.1.0
 - Hyprland

**Additional context**
Debug logs for both the cases and in second case could only see 4 shows in the list 

[lobster_log.txt](https://github.com/justchokingaround/lobster/files/12353644/lobster_log.txt)
![2023-08-16T04:35:42,513087794+05:30](https://github.com/justchokingaround/lobster/assets/104411772/fe0730a1-a859-48ce-a914-86ca2827bc76)
![2023-08-16T04:36:03,943377417+05:30](https://github.com/justchokingaround/lobster/assets/104411772/cf059f55-fe30-409f-8c87-7b53ed8760d3)
![2023-08-16T04:36:27,611727954+05:30](https://github.com/justchokingaround/lobster/assets/104411772/53f97ce5-eddf-450e-88a4-53834b53d107)
![2023-08-16T04:37:18,873482398+05:30](https://github.com/justchokingaround/lobster/assets/104411772/1c6d2b3e-a263-4eea-b473-d0a14676abf5)

Edit-1 : Some spelling mistakes

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
