### ISSUE TITLE
Image preview related options should not be set if image preview is not requested

### ISSUE THREAD

**Issue by 097115** [justchokingaround/lobster#156]
May be something like this could help:

    -        [ -z "$preview_window_size" ] && preview_window_size=up:60%:wrap
    -        [ -z "$ueberzug_x" ] && ueberzug_x=10
    -        [ -z "$ueberzug_y" ] && ueberzug_y=3
    -        [ -z "$ueberzug_max_width" ] && ueberzug_max_width=$(($(tput lines) / 2))
    -        [ -z "$ueberzug_max_height" ] && ueberzug_max_height=$(($(tput lines) / 2))
    +        ! [ "$image_preview" -eq 0 ] && [ -z "$preview_window_size" ] && preview_window_size=up:60%:wrap
    +        ! [ "$image_preview" -eq 0 ] && [ -z "$ueberzug_x" ] && ueberzug_x=10
    +        ! [ "$image_preview" -eq 0 ] && [ -z "$ueberzug_y" ] && ueberzug_y=3
    +        ! [ "$image_preview" -eq 0 ] && [ -z "$ueberzug_max_width" ] && ueberzug_max_width=$(($(tput lines) / 2))
    +        ! [ "$image_preview" -eq 0 ] && [ -z "$ueberzug_max_height" ] && ueberzug_max_height=$(($(tput lines) / 2))

Or, more probably, there's a better way :)

Of course, setting those even if not specifically requested may not seem that harmful at first but a) with no terminal available, using `tput` results in further calculations may lead to an error (you can't divide nothing by 2) and b) why really do it if there's no need? :)

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976

**Comment by 097115** [comment]
@justchokingaround 

Have you tried running `lobster --rofi`, though? Because it pushes links to thumbnails to the menu, not the suggested names (as with fzf).

**Comment by justchokingaround** [comment]
can you send a log please? `lobster -x` and then it will be in `/tmp/lobster.log`

**Comment by 097115** [comment]
The log is here: https://paste.rs/dTRtr

Seems like my rofi wants another Tab at the end of the line to show the last column. If I force add it, like this:

    choice=$(printf "%s" "$response" | awk '{print $0"\t"}' | rofi -dmenu -i -p "" -mesg "Choose a Movie or TV Show" -display-columns 4)

...then the titles are shown :)
