### ISSUE TITLE
Not a URL/Stream, script did not run

### ISSUE THREAD

**Issue by Kabouik** [justchokingaround/lobster#157]
**Describe the bug**
I just found out about `lobster` and love it. However, I seem to be having the following issue with the majority of things I have tried to test the script.

```
Search Movie/TV Show: sopranos                                                                                                                    
[vo/gpu/opengl] Could not choose EGLConfig for Desktop OpenGL!
Resuming playback. This behavior can be disabled with --no-resume-playback.
Playing: -
[ytdlautoformat] Not a URL/Stream, script did not run. 
[file] Reading from stdin...
```

`mpv` opens but nothing is fetched.

I got the issue with all movies or TV shows I tried (Sopranos, Shameless, Breaking Bad), then tried the `-t` option to test featured movies, and there the last Indiana Jones worked. I am not sure it is necessary to name them, but it might be easier to reproduce the issue that way.

**To Reproduce**
1. Clone latest commit
2. Run `./lobster.sh` and pick one of the abovementioned movies or TV shows (but surely there are many others, as only one worked for me)

**Expected behavior**
I would expect all movies/shows to play, or alternatively to throw a more detailed error helping to understand what caused the failure.

**Smartphone (please complete the following information):**
 - Device: F(x)tec Pro1
 - OS: Droidian (Trixie)
 - Browser: Chromium, Firefox; but not sure what is the relevance there as I only ran `lobster` in terminal (`foot`) and don't see how it could interact with the browser

**Comment by justchokingaround** [comment]
can u send me full logs by running `./lobster.sh -x` and then going through the same steps again pls? it will be a file located in `/tmp/lobster.log`

**Comment by Kabouik** [comment]
Sure, here's one sample with the TV show Deadwood for instance. Maybe it's just that there is no valid URL for it? I'm not familiar with how `lobster` works under the hood (*i.e.*, whether it would show a match if there was no valid URL for it 
in the first place).

[lobster.log](https://github.com/justchokingaround/lobster/files/12626106/lobster.log)

**Comment by justchokingaround** [comment]
there is no problem with the script itself, it's just that ur mpv fails to open the link. try downloading yt-dlp, or updating it if u already have it installed

**Comment by justchokingaround** [comment]
![Screenshot_20230916_072017_Termux.jpg](https://github.com/justchokingaround/lobster/assets/44473782/55b8576a-e743-4069-9335-45e782eeeb07)

![Screenshot_20230916_071954_mpv.jpg](https://github.com/justchokingaround/lobster/assets/44473782/fc9e2c25-5bf4-48e3-9c10-3de47eaea9d4)

**Comment by Kabouik** [comment]
Maybe my `yt-dlp` needs an update then, thanks!
