### ISSUE TITLE
Sometimes fills the terminal with seemingly random characters when `ueberzugpp` thumbnails are enabled

### ISSUE THREAD

**Issue by Kabouik** [justchokingaround/lobster#158]
**Describe the bug**
The below video shows what I observe with `lobster` when enabling thumbnails with `ueberzugpp`. This is in `foot`, but the same happens with other terminal emulators. It doesn't happen with `ytfzf`, which makes me think it might be specific to `lobster`, but I opened an issue at the `ueberzugpp` repository too just in case.

Here are the logs: [ueberzugpp-droidian.log](https://github.com/jstkdng/ueberzugpp/files/12629156/ueberzugpp-droidian.log), [lobster.log](https://github.com/justchokingaround/lobster/files/12629229/lobster.log)

**To Reproduce**
You can see first with `./lobster` that when I scroll slowly and images don't change too fast, there is no issue. However if I scroll faster, then immediately the issue occurs. Later, after I cleared the screen, you can see that the issue occurs directly when I use `./lobster -t` (which shows a much longer list of movies; more text and more rows).

**Expected behavior**
Working `ueberzugpp` previews.

**Video**
https://github.com/justchokingaround/lobster/assets/7107523/cd0faa11-0fe4-4b3e-be69-825d9366c18d

**Smartphone (please complete the following information):**
 - Device: F(x)tec Pro1
 - OS: Droidian (Trixie)
 - Terminal:  `foot`
 - Browser: Chromium

https://github.com/justchokingaround/lobster/assets/7107523/d37ba03d-2042-4d0d-9d93-66cd5cbc5d1d

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
