### ISSUE TITLE
For some medial files, it says "No Such file or directory"

### ISSUE THREAD

**Issue by ashhad** [justchokingaround/lobster#159]
**Describe the bug**
While using the download switch, in some cases a strange error is given. for example:
lobster -d mission impossible
/c/Users/<>/Mission: Impossible - Dead Reckoning Part One.mp4: No such file or directory
**To Reproduce**
Since this error occurs a few times and not with all titles it is a bit hard to produce

**Expected behavior**
movie should download as usual

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**

**Comment by justchokingaround** [comment]
use either `lobster -d '.' mission impossible` or `lobster mission impossible -d`
