### ISSUE TITLE
LOBSTER DOES NOT WORK FOR ME PLS HELP 

### ISSUE THREAD

**Issue by ConsiderKillingYourself** [justchokingaround/lobster#16]
**Describe the bug**
Lobster doesn't work. On running the lobster command, it takes too long to load the thing that will show me the options to choose my tvs show/movie. and when it does load, nothing shows up. 

**To Reproduce**
1. Install lobster normally. 
2. Run lobster in terminal. 
3. enter name of tv show you want to watch. 

**Expected behavior**
to be shown the thing that contains all the options for my tv show

**Screenshots**
![image](https://user-images.githubusercontent.com/112315510/187068826-d9125be2-902d-4576-bad6-646f61deac8f.png)

**Desktop (please complete the following information):**
 - OS: Endeavour OS 
 - Browser - Firefox 
 - Version - 104.0 (64-bit)

**Comment by justchokingaround** [comment]
does this website work for you in the browser? https://www5.himovies.to/

**Comment by ConsiderKillingYourself** [comment]
it loads for a very long time, and then it gives me an error message saying the connection has timed out. 
![image](https://user-images.githubusercontent.com/112315510/187070225-e1868021-b89e-4c22-a3f7-8885717316c5.png)

**Comment by justchokingaround** [comment]
consider using a vpn or a proxy, like 1.1.1.1 for example. if the website doesn't work for you, the script won't either

**Comment by ConsiderKillingYourself** [comment]
okay 
thank you very much

**Comment by ConsiderKillingYourself** [comment]
okay 
thank you very much
