### ISSUE TITLE
Not working on termux 

### ISSUE THREAD

**Issue by ashhad** [justchokingaround/lobster#160]
**Describe the bug**
I have tried installing lobster on termux as described on both the reddit page and the GitHub page but the application fails to play any media.

Sometimes it will show results and ask to choose option and then the script execution stops. Sometimes it gives "not found" for the same title

**Expected behavior**
Application should play media

**Screenshots**

 - Device: OnePlus 3
 - OS: lineage18
 - Browser chrome

**Additional context**

**Comment by justchokingaround** [comment]
termux support is outside of the scope of this project. i recommend u to use the cloudstream3 mobile app instead
