### ISSUE TITLE
Support for films/shows in other languages?

### ISSUE THREAD

**Issue by JetpackJackson** [justchokingaround/lobster#169]
**Is your feature request related to a problem? Please describe.**
I would like to be able to find both English and German films/shows with lobster.

**Describe the solution you'd like**
The ability to find shows in other languages, perhaps through an additional flag so only sources that have films in that language are parsed (in case you have to pull from a different source). Having an additional flag might also be helpful if the name of the movie in the other language is the same or similar as the english one.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by justchokingaround** [comment]
this is a planned feature for the rust rewrite, if you have website suggestions, send them here

**Comment by JetpackJackson** [comment]
Alright, that's awesome to hear! Kinox and kinoger[dot]to are ones that I know of for German. I unfortunately don't know any Rust but I'll see where I can help :+1:

**Comment by justchokingaround** [comment]
out of scope for the shell version. will consider it in the rust rewrite
