### ISSUE TITLE
base64: invalid input

### ISSUE THREAD

**Issue by MightyMoose504** [justchokingaround/lobster#174]
when attempting to use script it will peruse available content but upon selecting an episode or movie you'll be met with "base64: invalid input". Ive attached a log file. Let me know if you need any more info. Thanks!
[lobster.log](https://github.com/justchokingaround/lobster/files/13679342/lobster.log)

**Comment by JetpackJackson** [comment]
I'm also experiencing this issue, and I have a log file from the output of `lobster -x` as well: 
[log.txt](https://github.com/justchokingaround/lobster/files/13679810/log.txt)

**Comment by Javverrr** [comment]
Same

**Comment by aryan-212** [comment]
Same

**Comment by justchokingaround** [comment]
does this happen for all shows/movies ?

**Comment by JetpackJackson** [comment]
I tried again twice with a different show and the one I had originally tried, and they work, so I'm not sure what the bug was. I've attached the logs but I'm not sure how helpful they'll be.

[log3.txt](https://github.com/justchokingaround/lobster/files/13693889/log3.txt)
[log2.txt](https://github.com/justchokingaround/lobster/files/13693890/log2.txt)

**Comment by TheHighGroundWins** [comment]
Same I also have this problem

**Comment by Py607** [comment]
> does this happen for all shows/movies ?

I also have this problem, It does happen for all shows/movies (or at least 10 I randomly selected to check), this is the output from the --debug option

[lobster_log.txt](https://github.com/justchokingaround/lobster/files/13800032/lobster_log.txt)

**Comment by triorr** [comment]
```bash
$ base64 --v
base64 (GNU coreutils) 9.5
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Simon Josefsson.


$ echo -n U2FsdGVkX18U | base64 -d 
Salted__
$ echo -n U2FsdGVkX18U9 | base64 -d 
Salted__base64: invalid input
```

I narrowed down this error to two files base64.c in coreutils [here](https://github.com/wertarbyte/coreutils/blob/f70c7b785b93dd436788d34827b209453157a6f2/src/base64.c#L222) and base64.c in gnulib [here](https://github.com/coreutils/gnulib/blob/609921b1eef111f39291dc03d8996244d3dd13d2/lib/base64.c#L465)

```c
/* Decode base64-encoded input array IN of length INLEN to output array
   OUT that can hold *OUTLEN bytes.  The input data may be interspersed
   with newlines.  Return true if decoding was successful, i.e. if the
   input was valid base64 data, false otherwise.  If *OUTLEN is too
   small, as many bytes as possible will be written to OUT.  On return,
   *OUTLEN holds the length of decoded bytes in OUT.  Note that as soon
   as any non-alphabet, non-newline character is encountered, decoding
   is stopped and false is returned.  If INLEN is zero, then process
   only whatever data is stored in CTX.

   Initially, CTX must have been initialized via base64_decode_ctx_init.
   Subsequent calls to this function must reuse whatever state is recorded
   in that buffer.  It is necessary for when a quadruple of base64 input
   bytes spans two input buffers.

   If CTX is NULL then newlines are treated as garbage and the input
   buffer is processed as a unit.  */

bool
base64_decode_ctx (struct base64_decode_context *ctx,
                   const char *restrict in, idx_t inlen,
                   char *restrict out, idx_t *outlen)
```

As you can see in the comment above the `base64_decode_ctx` function there are multiple reasons that could trigger this error.

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
