### ISSUE TITLE
[Feature Request] Config to display  up to result pages of choice in advance for commands like lobster -r and lobster -r tv if possible

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#178]
A Config  that allows for displaying how many pages in advance ex. lobster -r tv but it display results up to user specified pages like up to page 2.
![1](https://github.com/justchokingaround/lobster/assets/95531944/2b0c8d8c-7f24-4645-86d1-070f6a0aa904)

**Comment by justchokingaround** [comment]
out of scope for the shell version
