### ISSUE TITLE
lobster not start when invoke with key binds

### ISSUE THREAD

**Issue by mazzi-ni** [justchokingaround/lobster#183]
**Describe the bug**
i tried to configure lobster in my config file of hyperland but it isn't work, it not show anything.
`bind = SUPER,M,exec,lobster -i --rofi -x -c`
i tried also in gnome to set a shourtcut in the setting but also here it not show anything

But when i try to execute it on a terminal work perfectly

![image](https://github.com/justchokingaround/lobster/assets/63593816/40f496ca-8ffc-4d4b-a26b-a87019d7c76f)
(in this image I used the same script by modifying the rofi settings to make it work on gnome 44)

![image](https://github.com/justchokingaround/lobster/assets/63593816/8dc944a7-eaf0-4737-8d07-dcd2058835f7)

**Comment by mazzi-ni** [comment]
![image](https://github.com/justchokingaround/lobster/assets/63593816/1a4fcd26-697a-4df2-a110-0f58990aa0dd)

this line for gnome is the problem but i don't know why.
I removed that line and now it work.

**Comment by justchokingaround** [comment]
omg thanks a lot. i remember this bug and after troubleshooting i found out the same thing, but never came aruond fixing it. thanks for reminding me what the problem was! i'll fix it when i get some time, but probably not soon 😔

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
