### ISSUE TITLE
lobster broken atm

### ISSUE THREAD

**Issue by CrimsonKiss** [justchokingaround/lobster#184]
when searching for a movie or series, it works as intended until I select the one I want to watch, afterwards, mpv does not open, neither does it work for vlc, there is no output on the terminal either

**Comment by justchokingaround** [comment]
yep, the e4 keys decryption has changed, and the code hasn't been updated yet to adapt to the new mechanisms. unfortunately i have exams for the next 3 weeks, so i can only review PRs, but won't be coding any fixes 😔

sorry

**Comment by CrimsonKiss** [comment]
Oh, so in about a month's time this could be fixed if there isn't any other time impediment? 
If so, awesome!
And good luck with your exams!!!

**Comment by justchokingaround** [comment]
if nobody figures out the decryption and hosts keys that i can use for decrypting the video links in one month's time, then yes, i'll fix it in a month. otherwise it's a 2 mins fix on my end, if someone does do that, which is likely to happen tbh, ik a couple people who can

**Comment by pitsi** [comment]
Assuming that the key is the reason lobster does not work...

If I find a url to provide us with the key, does anyone have the required knowledge to modify the script and return it to this state which it had 3 months ago?

https://github.com/justchokingaround/lobster/commit/22648c80d6511fe3fa6d3995b037c089e10ca8ba

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/d05dfadd486f8e4ea635b4ce63108af1877dbf49

**Comment by pitsi** [comment]
Lol, my keys was not even close to what the script needed :D
