### ISSUE TITLE
Something broke lobster on mac

### ISSUE THREAD

**Issue by MickLib** [justchokingaround/lobster#19]
It's been working fine for a while now, but recently whenever I try to watch something new or continue from history it tries loading, then immediately says "Press Enter to save episode progress or Ctrl-C to exit (this will not reset your progress)"
After pressing enter and trying again it then says "/opt/homebrew/bin/lobster: line 184: [: : integer expression expected".
Line 184 is "[ "$resume_from" -eq -1 ] && resume_from=0"

**Comment by MickLib** [comment]
Never mind, reinstalling mpv did the trick.
Though it's still saying "/opt/homebrew/bin/lobster: line 184: [: : integer expression expected" when you go to the next episode, but it seems to work

**Comment by justchokingaround** [comment]
expect lobster to be broken atm, himovies started encrypting their video links. i'll fix this soon tm, just a little busy atm

**Comment by justchokingaround** [comment]
fixed in 32841b4d710a5e6d85ecbe3ccb699e8ddb9e97be
