### ISSUE TITLE
No subtitles found, Epsiode doesn't play

### ISSUE THREAD

**Issue by Cylis-Dragneel** [justchokingaround/lobster#194]
**Describe the bug**
I am trying to watch Avatar: The Last Airbender (the original tv show not the netflix one) and no episode plays and it just gives me a no subtitles found error and closes the program.

**To Reproduce**
1. Do: ```$ lobster avatar```
2. Select Avatar: The Last Airbender (tv) [EPS 21]
3. Select Book One: Water and select any episode
4. The error: 
``` sed: -e expression #1, char 0: no previous regular expression No subtitles found```

**Expected behavior**
The episode should play regardless of if subtitles are found as I am trying to watch an english show, while my default subtitles are in english too. This shouldn't be a thing or at least should be a toggle of sorts.

 - OS: Arch Linux

**Additional context**
I used curl to download lobster and put it in my path instead of downloading from the AUR

**Comment by justchokingaround** [comment]
#193 duplicate
