### ISSUE TITLE
Lobster doesn't work

### ISSUE THREAD

**Issue by caliarch** [justchokingaround/lobster#196]
Message "PLEASE PURCHASE TO USED" displays when playing any movie/show and then mpv just quits.

1. Run lobster with search query
2. Click on any movie/show
3. Starts playing 
4. See message "PLEASE PURCHASE TO USED"

I expected to be able to watch something from the cli.

 - OS: Linux (Arch Linux)
 - Browser: Firefox
 - Version: latest and greatest

![2024-03-23-10:18:16-screenshot](https://github.com/justchokingaround/lobster/assets/152654510/6a4a70e6-27ff-4f81-b6da-1a171ca55888)

**Comment by justchokingaround** [comment]
you can use https://github.com/justchokingaround/superstream-cli/blob/main/superstream.sh as a temporary solution or wait until i fix lobster

**Comment by caliarch** [comment]
Aight, thanks, God bless!

**Comment by BakrAsskali** [comment]
It works now, i guess the problem was with UpCloud/VidCloud bot with lobster

**Comment by justchokingaround** [comment]
nah, worst case scenario i'll just change providers

**Comment by justchokingaround** [comment]
closing as duplicate of #193
