### ISSUE TITLE
When selecting from the history, the cursor is on the first entry from the history file, not on the last one

### ISSUE THREAD

**Issue by 097115** [justchokingaround/lobster#2]
If the history file contains three entries

    TV Show A Ep(1)
    TV Show B Ep(2)
    TV Show C Ep(9)

then the most recently watched would be *TV Show C*, is this correct? And when selecting an entry from the history, it would be logical to make it the default selection, what do you think?

If you agree, then adding `--tac` option to the `fzf` call would solve this (it will reverse the order of the input, making the most recently watched show actually the first in the selector).

**Comment by justchokingaround** [comment]
yes, i completely agree with this, and have actually been meaning to fix this for a while, just never actually did. ty for ur find, and feel free to open a pr get a contributor status 🙏

**Comment by 097115** [comment]
>  to open a pr get a contributor status 

Would be great if you could just add it yourself, it will save us time :) (no credits needed, too). Thanks!

**Comment by justchokingaround** [comment]
aight, no problem, ty <3
