### ISSUE TITLE
The script stop working suddenly

### ISSUE THREAD

**Issue by Visone-Selektah** [justchokingaround/lobster#20]
**Describe the bug**
Launch the script, show the header, choose something tv/movie. Until this all works. 
Choose tv, season,episode, And just enter in a loop, try to find the media but exit and show the msg 
{{{
Press Enter to continue watching, or Ctrl+C to exit
Loading TV: SX Ep X...
Press Enter to save episode progress or Ctrl-C to exit (this will not reset your progress)
}}}
All works fine in firefox and qutebroser in both void linux and venom linux

**Comment by olivluca** [comment]
see issue #19

**Comment by Visone-Selektah** [comment]
After almost 24h it started to work again.
I gues it was some token, captcha or network problem.
I'll close the issue
