### ISSUE TITLE
There's a weird issue not letting me play an episode 

### ISSUE THREAD

**Issue by Asriel115** [justchokingaround/lobster#202]
I am trying to play this in WSL 2 on Windows 11, I have zero issues with ani-cli however there seems to be some weird bug causing the whole thing to close failing to find subtitles when I try to play a selected episode
![image](https://github.com/justchokingaround/lobster/assets/63687010/0e17222d-cab6-46ea-bab8-3b7683c9735f)

**Comment by pitsi** [comment]
You must be new here :D
https://github.com/justchokingaround/lobster/issues/193

**Comment by justchokingaround** [comment]
dd205d91b703df3d6d41a6d617c96a35a45d42b7
