### ISSUE TITLE
Lobster does not parse any existing subtitles because their languages are labeled differently

### ISSUE THREAD

**Issue by pitsi** [justchokingaround/lobster#204]
**Describe the bug**
I started using lobster again now that the boys s04 started and I noticed the following. Although I have my subtitles language set to english in the config file, and although the api does return urls for them, it "labels" them differently and they are not picked up by lobster itself, so I get no subtitles.

Please note that it does not always happen but on SOME occasions. 

**To Reproduce**
1. Make sure you have set your prefered subtitles language in lobster_config.txt to english (for the example).
2. Search for something as usual, e.g. the boys s04e01 (nsfw series, you are warned), and play it. 
3. Notice there are no subtitles.

**Expected behavior**
The video should have subtitles.

**Screenshots**
Not needed. Any details and proof are under additional context below.

**Desktop (please complete the following information):**
 - OS: Debian testing/unstable x64
 - Player: mpv 0.38
 - Version: 4.2.7

**Additional context**
I got the video and subtitles urls in json output with lobster -j and pasted them in a file. Then I used jq to prove my point.
This is how the whole file looks
```
$ cat lobsteroutput | jq .
{
  "sources": [
    {
      "file": "(4 lines long url)",
      "type": "hls"
    }
  ],
  "tracks": [
    {
      "file": "(small url ending in .vtt)",
      "label": "Arabic - Arabic",
      "kind": "captions"
    },
    {
      "file": "(small url ending in .vtt)",
      "label": "Basque - Basque (Spain)",
      "kind": "captions"
    },
(other subtitles go here)
  ],
  "t": 1,
  "server": 18
}
```
And this is how all the languages are labeled
```
$ cat lobsteroutput | jq .tracks.[].label
"Arabic - Arabic"
"Basque - Basque (Spain)"
"Catalan - Catalan (Spain)"
"Chinese - Chinese Simplified"
"Chinese - Chinese Traditional"
"Czech - Czech (Czechia)"
"Danish - Danish"
"Dutch - Dutch"
"English - English [Forced]"
"English - English [SDH]"
"Finnish - Finnish"
"French - French"
"French - French Canadian"
"Galician - Galician (Spain)"
"German - German"
"Greek - Greek (Modern)"
"Hebrew - Hebrew"
"Hindi - Hindi"
"Hungarian - Hungarian"
"Indonesian - Indonesian"
"Italian - Italian"
"Japanese - Japanese"
"Kannada - Kannada (India)"
"Korean - Korean"
"Malay - Malay"
"Malayalam - Malayalam (India)"
"Norwegian - Norwegian"
"Polish - Polish"
"Portuguese - Portuguese"
"Portuguese - Portuguese Brazilian"
"Romanian - Romanian (Romania)"
"Russian - Russian"
"Spanish - European Spanish"
"Spanish - Latin America Spanish"
"Swedish - Swedish"
"Tamil - Tamil"
"Telugu - Telugu"
"Thai - Thai"
"Turkish - Turkish"
"Ukrainian - Ukrainian (Ukraine)"
```
Changing the subs_language setting to e.g. "English - English [Forced]" restores the intended functionality.

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/942ad9f466a1056fe48961826c1ff34da4beb976
