### ISSUE TITLE
sed unused label

### ISSUE THREAD

**Issue by Tadashi-BM-Hamada** [justchokingaround/lobster#206]
**Describe the bug**
When using FreeBSD an error regarding sed appears.

**To Reproduce**
1. Install lobster using curl
2. Input movie name
3. Error

**Expected behavior**
when using any Linux distribution lobster scrapes the site and then opens the movie in mpv, I just want to be able to do the same.

**Screenshots**
![20240616_19h18m43s_grim](https://github.com/justchokingaround/lobster/assets/99095862/a8199b36-af95-41f3-a741-298c48935d73)

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.1

**Additional context**
Linux emulation has been added as seen below:
![20240616_19h28m15s_grim](https://github.com/justchokingaround/lobster/assets/99095862/e26ba5ff-36f1-4c39-a87f-52c3d7de4b72)
# UPDATE: Install gsed and using your favorite stream editor replace all instances of sed with gsed, now it works like a charm.

**Comment by justchokingaround** [comment]
that happens bc that specific sed command only works with gnu-sed and not bsd sed. is there any way to download gnu-sed on FreeBSD?

**Comment by Tadashi-BM-Hamada** [comment]
I'll try it and see, thanks!
