### ISSUE TITLE
image preview error

### ISSUE THREAD

**Issue by Syzole** [justchokingaround/lobster#220]
**Describe the bug**
When attempting to use the image preview function the message:
"Aborted
cat: /tmp/lobster/.d79dd737-b07e-46cd-96ea-2181947b0681: No such file or directory"

**To Reproduce**
1. Run lobster -i
2. Search for media and have a blank box above
3. Ctrl + c to exit the script and see the error message above

**Expected behavior**
It should display the images

**Screenshots**
![image](https://github.com/user-attachments/assets/98962d56-fb6f-4814-a8c0-a771f3489031)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Terminal: WSL 2 Ubuntu-22.04
 - Lobster Version: 4.2.8

**Additional context**

**Comment by justchokingaround** [comment]
image preview isn't supported on windows (wsl included)
