### ISSUE TITLE
netlify.app is down

### ISSUE THREAD

**Issue by rahuloberai** [justchokingaround/lobster#227]
https://lobster-decryption.netlify.app link is down. 
can you please have check. what happened?

**Comment by rahuloberai** [comment]
Site Not found.

**Comment by justchokingaround** [comment]
I didn't pay the bill

**Comment by rahuloberai** [comment]
is there any alternate way to decrypt the data?

**Comment by rahuloberai** [comment]
> I didn't pay the bill

If possible can you please share the code

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster-netlify-api

**Comment by rahuloberai** [comment]
I did, getting 404 page
![Screenshot_2](https://github.com/user-attachments/assets/ad4a7996-e29e-4991-9c73-6c6204056acf)

**Comment by rahuloberai** [comment]
@justchokingaround Now its working thanks a lot. 
There was some configuration issue :)
