### ISSUE TITLE
No subtitles found error

### ISSUE THREAD

**Issue by anonymousje** [justchokingaround/lobster#228]
**Describe the bug**
Try to search for a show, select the episode and error "No subtitles found" occurs. 

**To Reproduce**
1. lobster iron man
2. select iron man

**Expected behavior**
VLC or MPV should open to play the video

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Version 4.3.2

**Comment by MrCraft18** [comment]
Same exact issue on Linux Mint.

**Comment by AndreidForGit** [comment]
Same on Ubuntu and android

**Comment by sbhta** [comment]
same issue on arch

**Comment by pitsi** [comment]
Same issue on... (nevermind).

The real issue is not the subtitles or anything similar like their language. The main url lobster uses in order to decrypt what is needs now leads to a 404. In turn, the json_data variable contains gibberish instead of links for video and subtitles which are passed to the player which will play them. 
Unfortunately, the script does not have an info line that would say "no video", like it has for the lack of subtitles, so the user is only about the lack of subtitles and nothing more.

So, until justchockingaround fixes the used domain or creates a new one, nothing can be done.

**Comment by No-Biggie805** [comment]
For now there seems to be a workaround posted on [discord](https://discord.com/channels/1116043583024283909/1116050000544288818/1283132995896606803)
I would recommend a (distrobox,toolbox) container for this if possible for testing, i myself had it tested on a VM inside EndeavourOS.

**Comment by pitsi** [comment]
Too bad I am not on discord then :(

**Comment by rahuloberai** [comment]
https://lobster-decryption.netlify.app/
Site is down because @justchokingaround did not pay the bill for netlify. 
Use this repository https://github.com/justchokingaround/lobster-netlify-api as a backend service.

**Comment by pitsi** [comment]
Ahhh selfhosting :D 

That is what I tried yesterday. I installed nodejs/npm, cloned the repo, run npm install to install any dependencies, then npm start and it failed. What did I do wrong? Alpine edge guest vm, running on virtualbox, on debian unstable host, both x64.

**Comment by No-Biggie805** [comment]
> Ahhh selfhosting :D
> 
> That is what I tried yesterday. I installed nodejs/npm, cloned the repo, run npm install to install any dependencies, then npm start and it failed. What did I do wrong? Alpine edge guest, running on virtualbox, on debian unstable host, both x64.

You need netlify, and inside the repo you cloned, do `npm i` and then `netlify dev`, if it tries to find a browser discrived(yes i had this issue too even though it was uninstalled, it was looking for cachy-browser), either configure netlify or just install that specific browser its looking for xp..

**Comment by pitsi** [comment]
I have no netlify binary after installing it with npm. I guess it is because I did not allow it to install globally.
Nevermind, I will wait for the dev to fix the site. 

If someone has his own domain, please consider hosting the decrypter thing.

**Comment by FurqanHun** [comment]
you don't need to install the netlify binary globally, i did read the message on discord and then tried setting it up. At first i thought maybe i could modify it to run as a nodejs server but then gave up (idk nodejs), and then just used netlify cli.

- You do need nodejs and npm installed (which btw might already be installed if you're on fedora)
1. Clone [lobster-netlify-api](https://github.com/justchokingaround/lobster-netlify-api)
2. Open the local directory in terminal and run `npm i` or `npm install`
3. Run `lobster --edit` and add the following in the config:
```
    json_from_id() {
      json_data=$(curl -s "http://localhost:8888/.netlify/functions/decrypt?id=${source_id}")
    }
```
_by default netlify server would run on 8888 but if it doesn't change it to whatever port it runs on_
 - if it says that a config doesn't exist, you can create one using `touch /home/YOUR_HOST_NAME/.config/lobster/lobster_config.sh` (change the YOUR_HOST_NAME to your username and then add it to the config.
4. Run `netlify dev` (if you didn't installed netlify globally you can execute it using `npx netlify dev` as running `npm i` should've installed it as a dependency under the project, but you should be in the project directory).

- don't close the terminal or the server will stop... and you'd need to start the server using `netlify dev` (or `npx netlify dev` in the project directory) each time you wanna use lobster, unless you run it all the time or set it to start at boot ig.

If you don't want to run a local server you can host it on netlify, then in the config you'd add something like `https://your-sub-domain.netlify.app/.netlify/functions/decrypt?id=${source_id}` tho i haven't tested that myself. Also you'd have to configure build settings while deploying.

_Btw when you run the server using `netlify dev` or `npx netlify dev` it would show 404 after opening it up on default browser and it would shift to the static version as you don't have all the things needed but it still works fine_

## Screenshots
### running server using npx netlify dev
![image](https://github.com/user-attachments/assets/cef6dfac-f69f-474f-8f64-44754139e7aa)

### the page shows 404 but its fine
![image](https://github.com/user-attachments/assets/5c0d4c81-72cd-432e-9de6-d6d51c307228)

### lobster should work now...
![image](https://github.com/user-attachments/assets/9e3ca1e7-cbe1-4d09-b420-676cceddc9fb)

**Comment by pitsi** [comment]
Thank you for the very detailed explanation. 

Out of all the things you describe above, the only think I would not even think to do is the npx one on step 4. So, I managed to make the server run, I saw the text on your first screenshot as it scrolled up and it ended up with this
```
 ›   Error: There was a problem setting up the Edge Functions environment. To try a manual installation, visit https://ntl.fyi/install-deno.
(node:2838) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
I ignored it, opened a browser on `http://alpine.local:8888` and saw the 404 message you mention. But when trying curl on it with an id (the ones mentioned below are valid and are for deadpool), I got an "internal server error" on the client side
```
$ curl http://alpine.local:8888/.netlify/functions/decrypt?id=1612803
{"error":"Internal server error"}

$ curl http://alpine.local:8888/.netlify/functions/decrypt?id=19694
{"error":"Internal server error"}
```
and these on the server side
```
Request from ::ffff:192.168.1.2: GET /.netlify/functions/decrypt?id=1612803
TypeError: Cannot read properties of null (reading '0')
    at getMeta (/root/lobster-netlify-api/netlify/functions/rabbit.ts:720:31)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at newReq (/root/lobster-netlify-api/netlify/functions/rabbit.ts:727:7)
    at main (/root/lobster-netlify-api/netlify/functions/rabbit.ts:778:10)
    at Object.handler (/root/lobster-netlify-api/netlify/functions/decrypt.ts:16:20)
Response with status 500 in 682 ms.

Request from ::ffff:192.168.1.2: GET /.netlify/functions/decrypt?id=19694
TypeError: Cannot read properties of null (reading '0')
    at getMeta (/root/lobster-netlify-api/netlify/functions/rabbit.ts:720:31)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at newReq (/root/lobster-netlify-api/netlify/functions/rabbit.ts:727:7)
    at main (/root/lobster-netlify-api/netlify/functions/rabbit.ts:778:10)
    at Object.handler (/root/lobster-netlify-api/netlify/functions/decrypt.ts:16:20)
Response with status 500 in 230 ms.

``````
It goes without saying that 192.168.1.2 is my pc's ip and that I use avahi (mdns) on every system on network, so instead of the ip of the alpine vm, I use alpine.local, because
```
$ avahi-resolve -n alpine.local
alpine.local	192.168.1.104
```

**Comment by FurqanHun** [comment]
### Using the curl manually it does give 500:
![image](https://github.com/user-attachments/assets/ae6d8d4c-8fe0-494e-b9eb-1dd0f946c78f)
### However directly using lobster somehow works:
![image](https://github.com/user-attachments/assets/054d4344-05ab-486d-9a33-1a60abdcc505)
### here's the ss of server terminal:
![image](https://github.com/user-attachments/assets/2236b97a-fe6d-454b-a80e-afc484442228)


directly scrapping thorugh curl did gave 500, however when using lobster it somehow worked though there still are some errors `Invalid input string format: window.ReactNativeWebView`


Now here's what i think, FlixHQ probably changed some things (cuz its using different ids when using lobster), but that doesn't answer why the api can't be deployed on netlify (i've tried to deploy it but rabbit.ts causes the build to fail) or maybe netlify changed some things or maybe i'm doing it the wrong way idk...

**Comment by pitsi** [comment]
You are right about running curl alone, it returns no results. Thank you for enlightening me! :)
One minor annoyance I found. On line 379 that holds the url for the json_data variable, the https part had to be changed to http for the whole thing to work.

**Comment by justchokingaround** [comment]
the plan is to switch from netlify to https://www.koyeb.com/ (afaik it has unlimited requests for free unlike netlify), I just haven't had time yet to do so, as I'm very busy (physically) atm. if anyone can help with the setup of the API it would be very helpful. otherwise u can just wait for me to do it.

**Comment by justchokingaround** [comment]
ty @pitsi for the original explanation and thanks a lot @FurqanHun for the elaborate explanation of how to self host the decryption API server, that helps people out a lot and I haven't done it yet <3

**Comment by judexgauss** [comment]
@justchokingaround still having this issue on arch linux, lobster version 4.3.3.

![image](https://github.com/user-attachments/assets/e62b5e66-e861-411a-b362-c6cffe118e64)

**Comment by pitsi** [comment]
It is because the new site that lobster uses now leads to a 404. Curl parses its entire page as an html, so the contents of the json_data variable are gibberish again and in turn the script fails to run. Basically whatever I explained last time.

**Comment by FurqanHun** [comment]
@judexgauss @pitsi this is a non issue, and even if the api was working the site would still show 404 cuz there's no frontend… anways the reason is the new site of migration randomly banned the dev :( (maybe alts too idk), the only solution for now is to self host, either locally or on a service like netlify…
