### ISSUE TITLE
Trending option not working

### ISSUE THREAD

**Issue by Spaxly** [justchokingaround/lobster#26]
title

**Comment by justchokingaround** [comment]
i removed this feature, due to the fact i switched to using an api instead of directly web scraping. since it's requested, i'll implement it back

**Comment by Spaxly** [comment]
oh, ok, thanks u.

**Comment by Spaxly** [comment]
Any update on this @justchokingaround ?

**Comment by justchokingaround** [comment]
will take a look in the upcoming days

**Comment by Spaxly** [comment]
@justchokingaround you can use the Top IMDB section directly from the website instead of scraping through API. I will take a look to implement this later and make a PR.

**Comment by ttx99** [comment]
is it possible to request this to the api maintainer?

**Comment by Spaxly** [comment]
> is it possible to request this to the api maintainer?

You could try, but would be better if done on the script-end.

**Comment by justchokingaround** [comment]
closing in favor of #47
this will be done in the v4 pr:
https://github.com/justchokingaround/lobster/pull/54
