### ISSUE TITLE
Saved progress jumped into 'Season', not 'Episode'

### ISSUE THREAD

**Issue by EnigmaticJihad** [justchokingaround/lobster#27]
**Describe the bug**
When watching Tv shows, saved progress jumped into the next season, not the next episode.

**To Reproduce**
1. Watch an episode from a Tv show. 
2. Quit the player (`q` for `mpv`)
3. Press `enter` to save the progress.
4. Press `enter` again to continue watching.
5. It'll show the next season, not the next episode.

_[I was watching Star wars:The clone wars season 1 - episode 11, pressed `enter` to save the progress, and pressed `enter` again to continue watching, it showed season 2 - episode 1, not season 1 - episode 12. Reproduced the error 2 times.]_

**Expected behavior**
Next episode will be shown in continue watching.

**Screenshots**
![screenshot-selected-221008-0012-20](https://user-images.githubusercontent.com/36424076/194623081-4f7bd99a-86fe-4ee7-8a3b-d1800910b1d3.png)

**Comment by justchokingaround** [comment]
ok so i've troubleshooted, and it seems to be a problem with every single show i've tested. not sure yet why it happens, but it's definitely a mistake i made inside the script. will fix in the upcoming days

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/commit/b55a9d87564845b7a0fdffc337a26c77521384ce 
should fix it. please test it and tell me if anything doesn't work, i haven't thoroughly tested the fix

**Comment by EnigmaticJihad** [comment]
**The fix is working.**
