### ISSUE TITLE
Lobster tells me there's no link

### ISSUE THREAD

**Issue by HopeTrash** [justchokingaround/lobster#30]
wanted to watch destruction babies and it came up with no links even though it is on the provider's website.

**Comment by ttx99** [comment]
for me it's my isp cause if I use vpn it works, but there are instance that it works without using vpn. Just my observation.

**Comment by HopeTrash** [comment]
Forgot to mention it only does that to this specific movie

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/4949f7bebc7e35509fa82ebc6cb7c2d280744fca

**Comment by pavelskipenes** [comment]
@justchokingaround This commit does not seem to be fixing it. Can this issue be reopened?

**Comment by justchokingaround** [comment]
what problem exactly are you encountering?

**Comment by pavelskipenes** [comment]
It says no links found. If you tell me how to get more verbouse logs I'll be happy to provide

**Comment by justchokingaround** [comment]
1. run this to delete the old config file `rm ~/.config/lobster_config.txt`
2. if that didn't fix it, send me the output of
```sh
sh -x $(which lobster)
```

**Comment by justchokingaround** [comment]
flixhq is an unstable provider, they change their encryption keys every few hours so nothing i can rly do about it unfortunately. i dont know any better provider that could be scraped too.
:(

**Comment by justchokingaround** [comment]
it's back to working btw, but expect the script to be unstable every now and then. this will depend on how often flixhq change their encryption

**Comment by Spaxly** [comment]
@justchokingaround you can try novastream.

**Comment by justchokingaround** [comment]
might add some of its sources once i rewrite the project on a larger scale in rust

**Comment by ttx99** [comment]
> might add some of its sources once i rewrite the project on a larger scale in rust

https://vidsrc.me/

I dont know wtf is this... maybe u can
