### ISSUE TITLE
android mpv error "no file given"

### ISSUE THREAD

**Issue by 4cecoder** [justchokingaround/lobster#32]
**Describe the bug**
Running Lobster on android system fetches title then opens `mpv` succesfully but mpv says no file given

**To Reproduce**
1. Go to turmux install fzf and lobster
2. input any movie and then hit return key 
3. Mpv  opens displaying error (as  floating android toast message) then immediately closes  

**Expected behavior**
MPV should display the selected video stream

**Smartphone (please complete the following information):**
 - Device:  Google Pixel 4a
 - OS:  Android 13
 - Browser: Turmux (terminal emulator)

**Comment by pitsi** [comment]
Same thing happens here.
Something must have changed in the api's side, on the upcloud and vidcloud part. As it seems the search returns results as usual,  the results return info for the movie/series, but when it comes to servers, no urls are returned for upcloud and vidcloud. Mixdrop returns urls, but it does not work on lobster.
That is what I think the issue really is, but I will check it further later on.

Debian testing/unstable x64, mpv 0.34.1 and so on.

**Comment by pitsi** [comment]
I did my part and reported the api issue upstream so that its devs can check it.

**Comment by pitsi** [comment]
The api maintainers have fixed the issue so the api now returns links again to and lobster works like it used to!

You are welcome :)
