### ISSUE TITLE
Option to download the episod using Axel for example

### ISSUE THREAD

**Issue by EnkiOmoikane** [justchokingaround/lobster#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by justchokingaround** [comment]
done with ffmpeg in https://github.com/justchokingaround/lobster/commit/72b5752df1251d33c12a7f81627d1d20413be819, if you want axel support as well please reopen this issue
