### ISSUE TITLE
on number choice inputs ignore all blank spaces before the number

### ISSUE THREAD

**Issue by 4cecoder** [justchokingaround/lobster#35]
example:
 ```shell
choose season (1-4)
    1 
#_ <--- blank spaces here on input aren't accepted
 ```

program throws an error 

### possible solution 
implement a regexp or something to ignore all blank spaces before the number
 (just in case the user accidentally hits space bar before hitting enter)

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/pull/54
