### ISSUE TITLE
Feature Request: Show Trending/Popular Movie and/or TV Picks 

### ISSUE THREAD

**Issue by Spaxly** [justchokingaround/lobster#4]
Showing Trending/Popular movie or tv picks can be a great feature when trying to choose what to watch. A few ways is to parse an argument such as `-t` for trending and list all trending/popular picks in FZF. Another way is just to default this when launching lobster, either way, this would be a great feature that differs from the rest of CLI programs to watch content.

**Comment by justchokingaround** [comment]
sure, i'll look into implementing it

**Comment by Spaxly** [comment]
Great! If any help is needed with this, I am open!

**Comment by justchokingaround** [comment]
added it in the latest commit: https://github.com/justchokingaround/lobster/commit/a39d18639119343799037ad968ef0d8396a9363e
note that some movies that are provided by the Hydrax servers, won't work (most will work), and i don't plan on scraping that provider, bc it just doesn't seem worth it to me

**Comment by Spaxly** [comment]
Thanks!

**Comment by Spaxly** [comment]
Closing this request as completed.
