### ISSUE TITLE
lobster executes line 133 error

### ISSUE THREAD

**Issue by bachig26** [justchokingaround/lobster#41]
**Describe the bug**
This is the first that I'm running the lobster and when try to enter a TV Series, the program doesn't run the content as it executes an error saying `/usr/bin/lobster: line 133: [: : integer expression expected`.

**To Reproduce**
1. Go to 'lobster reborn rich'
2. Select 'Reborn Rich (TV Series)'
3. Enter 'Episode no 1'
4. Click on 'Enter for Saving the watch history'
5. See error

**Expected behavior**
I expect the program to run the content.

**Screenshots**

![1](https://user-images.githubusercontent.com/96393348/207319418-691124c6-85af-43e9-bbd7-50209366ec59.jpg)

![2](https://user-images.githubusercontent.com/96393348/207319431-1c0b7a63-9c21-4e30-9480-3caef10725c2.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by bachig26** [comment]
@justchokingaround please help me solve this issue.

FYI: I running the program on bash (admin) in cmder.

**Comment by Visone-Selektah** [comment]
I have the same error, but for me it woks after 2 `return` presses 
OS: Venom Linux

**Comment by bachig26** [comment]
> I have the same error, but for me it woks after 2 `return` presses OS: Venom Linux

for me, it keeps on looping...
i've tried multiple times, no improvement with it.

**Comment by bachig26** [comment]
i just now got an new error in addition to that line 133 error,

`/usr/bin/lobster: line 50: [: : integer expression expected`

**Comment by justchokingaround** [comment]
should be irrelevant after https://github.com/justchokingaround/lobster/commit/72b5752df1251d33c12a7f81627d1d20413be819, please test it
