### ISSUE TITLE
No links found

### ISSUE THREAD

**Issue by K5tsu** [justchokingaround/lobster#45]
I've been trying to watch multiple different shows and movies but it keeps saying "no links found"
i've restarted my pc and reinstalled but nothing is working

**Comment by justchokingaround** [comment]
flixhq change their encryption keys from time to time, so sometimes this might happen. usually it shouldn't take more than a few hours to work again. i am however looking into alternatives to fix this issue

**Comment by K5tsu** [comment]
Ok, Thank You
