### ISSUE TITLE
Support for new movies, new episodes and trending movies/series

### ISSUE THREAD

**Issue by pitsi** [justchokingaround/lobster#47]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem.

**Describe the solution you'd like**
The api now has endpoints for new movies, new episodes and trending movies and series. Their respective urls are
```
https://api.consumet.org/movies/flixhq/recent-movies
https://api.consumet.org/movies/flixhq/recent-shows
https://api.consumet.org/movies/flixhq/trending
```
**Describe alternatives you've considered**
Not applicable.

**Additional context**
The trending option lists 48 entries. The first 24 are always movies and the remaining 24 are always tv shows. There is no way to list movies or tv shows only. There is also no way to list more than that number of entries.

**Comment by ttx99** [comment]
> **Is your feature request related to a problem? Please describe.** No it is not related to a problem.
> 
> **Describe the solution you'd like** The api now has endpoints for new movies, new episodes and trending movies and series. Their respective urls are
> 
> ```
> https://api.consumet.org/movies/flixhq/recent-movies
> https://api.consumet.org/movies/flixhq/recent-shows
> https://api.consumet.org/movies/flixhq/trending
> ```
> 
> **Describe alternatives you've considered** Not applicable.
> 
> **Additional context** The trending option lists 48 entries. The first 24 are always movies and the remaining 24 are always tv shows. There is no way to list movies or tv shows only. There is also no way to list more than that number of entries.

Bro can you request to the api maintainer if they can also put the year released? 
This is why .... I'm actually looking for the 2022 one.
![Screenshot_2023-03-10_12-29-24](https://user-images.githubusercontent.com/95531944/224223734-7a546c0d-3c87-4792-8961-c9f9ed9c20e0.png)

**Comment by justchokingaround** [comment]
i will not be requesting any features from the api maintainers, since v4 does the scraping directly. i will however display the movies' years

**Comment by pitsi** [comment]
Although I think you should open a new request for that, I want to add that the api does return the year, but only for the movies. Here is the output of a small python script I made a while ago
```
0 Deadpool 2016
1 Deadpool 2 2018
2 Once Upon a Deadpool 2018
```

Last but not least, I wish I could maintain the script in its current bash format, but bash is too hard for me :(

**Comment by justchokingaround** [comment]
i won't be relying on the consumet api anymore, so the implementation will ne different, but thank you for sharing

**Comment by justchokingaround** [comment]
currently lobster has the option to change the instance in the config file, like this
```sh
base=https://api.haikei.xyz/movies/flixhq
```
but relying on an external api for scraping is always bound to be unstable to some extent

**Comment by pitsi** [comment]
That is why I plan on hosting my api instance... one day. 
For now, I am just relying on another instance and it works fine so far.

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/lobster/commit/72b5752df1251d33c12a7f81627d1d20413be819

**Comment by pitsi** [comment]
Can you please name the new version as 4.x instead of 3.9.9? it (= lobster) no longer uses the api for its functions, it is a complete rewrite that scrapes the web page itself. Thus it is no longer a "patch" for 3.x but a completely new thing.

And all this happens just a week after I decided to host my instance of the api locally so as to make lobster 3 work. :P

**Comment by justchokingaround** [comment]
thats is completely the idea. the only problem is that since it was a slighlty rushed release, there is likely to be many bugs, so i just let the testers know about the new release and i'll fix everything and release v4 in a few days

**Comment by pitsi** [comment]
I see. Let's wait then. I will give it a try when I have time.

p.s. I wish I was skilled enough to create a similar script that would use a working provider of the same api :(
