### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by breddie-is-rookie** [justchokingaround/lobster#49]
Lobster doesn't give any sort of output, when a series/movie is searched. Whenever I search something (for eg) `lobster breaking bad`, it outputs an empty list.

1. Installed lobster from AUR
2. Run the respective command

Output: 

![2023-02-18_13-29](https://user-images.githubusercontent.com/77089908/219849058-14a41c0c-263a-4bda-8420-668e7a865702.png)

 - OS: Arch Linux with KDE (and command used in konsole and yakuake)
 - Browser: Firefox
 - Version: 3.0.4

Additional context:
I came across a closed issue about the same error, but it was said to be due to the website (himovies). But even after using a VPN connection where the website is working, I get the same output.

**Comment by pitsi** [comment]
The server that is hosting the api used by lobster is experiencing downtime since last weekend (since 11th or 12th of February) and no one knows when it will be back up. Meanwhile, you can use a different one, like the one described on #48, by changing the "base=" parameter.

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/831aa8f41987385fad30e5ee4e382218a61d1c60
example config:
```sh
player=mpv
subs_language=English
video_quality=1080
base=https://api.haikei.xyz/movies/flixhq
preferred_server=vidcloud
```

**Comment by breddie-is-rookie** [comment]
Yo, thanks for the help, you really made my day

**Comment by pitsi** [comment]
And today the api page from the original url is back and working.
I reverted my config file to the previous base url.

**Comment by Aridlvory** [comment]
> And today the api page from the original url is back and working.
> I reverted my config file to the previous base url.

It dosent work for me

**Comment by justchokingaround** [comment]
can you use the v4 branch @Aridlvory for the time being (the history feature is missing but everything else should work). im doing a complete rewrite so it's taking me a bit of time

**Comment by Aridlvory** [comment]
Well V4 didn't work too
I am using termux
Anyway. Take your time and complete the work
I will wait
![Screenshot_20230504-190749_Termux.jpg](https://user-images.githubusercontent.com/78092537/236222161-f4647aed-6a9e-403e-a343-a0d7d12dac45.jpg)

This is what it shows
It dosent open mpv

**Comment by justchokingaround** [comment]
i will remove that perl dependency
