### ISSUE TITLE
Temporary break

### ISSUE THREAD

**Issue by justchokingaround** [justchokingaround/lobster#51]
I have somewhat lost motivation to maintain this project atm, and I currently have exams. I would love to make lobster great again, I have lots and lots of feature ideas that I already know how to and have implemented in my [jerry](https://github.com/justchokingaround/jerry) script, however I would like to completely rewrite lobster from scratch, so the code structure is easier to understand and maintain, and everything is more readable. I apologize for ignoring the issues, I will fix them all in the next big release, I can promise it will happen in less than a month. Sorry for the wait :pensive:

**Comment by ttx99** [comment]
- thx dude and I hope this will be as popular as ani-cli.  I hope you can bring coder friends with you to help maintain this script. This is probably imho opinion same or on par as ani-cli in terms of importance and relevance cause im pretty sure anime lovers also watch tv shows and movies. Take your time exam is important,  we have add block anyway lol.

thx bro

**Comment by pitsi** [comment]
And a thank you from me as well.
Well, as long as the api works and makes lobster work in turn, there is no reason to worry for more. 
But if you allow me a piece of advice, consider using jq in your script. It will save you a lot of time from those greps and seds.

**Comment by justchokingaround** [comment]
2 reasons actually, for why i use sed over jq:

1. jq would add an additional dependency which users would have to install externally
2. for simple json sed is faster than jq

**Comment by justchokingaround** [comment]
will delay by a few weeks, sorry eveyrone, life is a little rough

**Comment by port19x** [comment]
take your time m8
