### ISSUE TITLE
[minor] xdg compliance

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#52]
technically lobster_history.txt should have been in .local/share/lobster/

Does it matter? The logic of the xdg folders, is to allow easier data management. .cache can be safely deleted, .config needs some work to be recreated, .local is for user generated data that are the most valuable.

**Comment by justchokingaround** [comment]
good point, i will do that in v4.0.0

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/lobster/commit/72b5752df1251d33c12a7f81627d1d20413be819
