### ISSUE TITLE
[minor] end of series not taken into account in history

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#55]
**Describe the bug**

errors when reaching end of series with history
1. `/usr/bin/lobster: 63: [: grep: unexpected operator`
2. `/usr/bin/lobster: 63: cannot open /home/XXXX/.config/lobster/lobster_history.txt: No such file`

**To Reproduce**

1. start watching the very last episode, exit and save it in history
2. watch the last episode to the end
3. when ask to save progress, you get error 1

with no prior history at all
1. directly watch last episode to the end
2. try to save progress, error 2

**Expected behavior**
It should recognize it's at the end, instead of trying to save it.

**Desktop (please complete the following information):**
 - OS: Debian 11/amd64
 - Version 3.05

**Comment by justchokingaround** [comment]
will fix in v4, thx for letting me know :+1:
