### ISSUE TITLE
[BUG] Is it broken?

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#56]
The search is empty. Is it just me?

**Comment by justchokingaround** [comment]
![image](https://github.com/justchokingaround/lobster/assets/44473782/1f993dea-6ebf-4692-b7a0-fd993e940077)

The current main branch is broken, however the v4 branch should be working just fine (it is missing a few features atm, including history)

**Comment by justchokingaround** [comment]
Sorry for the inconvenience, I'm currently working on a whole new project that will have a movie scraper with many more features

**Comment by ttx99** [comment]
> Sorry for the inconvenience, I'm currently working on a whole new project that will have a movie scraper with many more features

How to install v4?
 Im noob at linux bro been using browser this whole time wtf.

**Comment by justchokingaround** [comment]
```sh
git clone "https://github.com/justchokingaround/lobster"
cd lobster
git checkout v4
sudo cp lobster.sh /usr/local/bin/lobster
cd .. && rm -rf lobster/
```
and run `lobster` in the terminal to use it, `lobster -h` to see the help menu

**Comment by ttx99** [comment]
[mac99@mac99-h170gaming3 ~]$ lobster 
Enter a query: sisu
Since only one entry was found, it was automatically selected
Getting the video links...
Playing Sisu
/usr/local/bin/lobster: line 214: socat: command not found
/usr/local/bin/lobster: line 214: socat: command not found
/usr/local/bin/lobster: line 214: socat: command not found

**Comment by ttx99** [comment]
but also how to uninstall this test script if the official script is released?

**Comment by justchokingaround** [comment]
`sudo rm $(which lobster)`

**Comment by justchokingaround** [comment]
i pushed v3.9.9 to main, everything should be fixed, check the `--help` to see the new features etc. i'll document everything properly later
