### ISSUE TITLE
XDG_DATA_HOME no default value

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#58]
you forgot  to define it, then it tries to create /lobster in configuration()

**Comment by justchokingaround** [comment]
what do you mean?
https://github.com/justchokingaround/lobster/blob/main/lobster.sh#L56

**Comment by justchokingaround** [comment]
show me the output of `echo $XDG_CONFIG_HOME`

**Comment by ttx99** [comment]
![Screenshot_2023-05-20_22-05-31](https://github.com/justchokingaround/lobster/assets/95531944/04182328-7eb0-4537-8cc0-c6b88e8d08d8)

**Comment by justchokingaround** [comment]
so that's why it's happening. i'll push a fix in a bit

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/d4edf635dfa38138566e24bb1435dd43d41e04d4, please test it and report back. for the script to work properly you will need to also install `html-xml-utils` and `socat` (i might make them optional dependencies later on, but right now it won't work without them)

**Comment by ttx99** [comment]
![Screenshot_2023-05-20_22-05-31](https://github.com/justchokingaround/lobster/assets/95531944/59f8368c-f659-42a0-8eab-b20b464a871f)

**Comment by justchokingaround** [comment]
my bad, i accidentally added an additional slash in the directory variable, please update again

**Comment by ttx99** [comment]
I dont know if this is an error or not but  I just wanna post it ...  I did not finish watching this movie.
![Screenshot_2023-05-22_19-22-54](https://github.com/justchokingaround/lobster/assets/95531944/442a9d76-902c-42dc-b999-43809b3b1a03)

**Comment by ttx99** [comment]
> this sometimes happens with socat, but i think i implemented a workaround that saves the progress in a file, and accounts for this edgecase. when you play this movie again (either by looking it up again, or using `lobster -c`, does it start from `00:02:09` ?

Yes, but personally I don't like it saving automatically I like it in v3 that it ask you if want to save progress.

**Comment by ttx99** [comment]
I dont know if this is my connection or what but when I play movies it loads faster but tv shows are slow and dropping. I'm not using vpn while doing this though.

**Comment by justchokingaround** [comment]
please open a separate issue, and specify for which movies and tv shows this happen specifically so i can test it
