### ISSUE TITLE
Watch history by minutes like on yt?

### ISSUE THREAD

**Issue by MickLib** [justchokingaround/lobster#6]
Hi! Love this program, but I was wondering whether it is possible to implement the ability to remember where you last stopped in minutes, like YouTube or Netflix.
Sorry if my English is rough

**Comment by justchokingaround** [comment]
this could technically be possible, using mpv's websockets with some additional tinkering in the history file, but it will certainly not be easy. i'll try to look into it further tomorrow but don't expect this feature very soon

**Comment by MickLib** [comment]
Thank you for responding so quickly, and good luck! :)

**Comment by justchokingaround** [comment]
@MickLib so, if i understand correctly, you'd want smtg like this?

https://user-images.githubusercontent.com/44473782/183246368-7b1f0e27-26e7-4d1e-949c-6948fe973e37.mp4

**Comment by MickLib** [comment]
@justchokingaround yes, exactly!

**Comment by justchokingaround** [comment]
gonna push in a few mins, just have to finish some error handling stuff

**Comment by justchokingaround** [comment]
@MickLib https://github.com/justchokingaround/lobster/commit/fcfbbcdeff31a7801d9c7b423e520cf73f5265af

added this feature in the latest commit. basically, it will prompt the user to ask if he wants to save his progress, and if he presses enter it will save the latest position. this works for both movies and tv shows. the movie or episode will get marked as completed when the user watches 85% of the video length. i'll document everything properly in the readme later

**Comment by justchokingaround** [comment]
you're gonna have to delete your history if u have the one from versions < 2.0.0 😔

**Comment by justchokingaround** [comment]
just found an edge case, which happens after watching the last episode of a season, fixing it rn

**Comment by MickLib** [comment]
I tested it, you can manually choose an episode, mark it as watched, and then the continue function works again. That's one way to do it without deleting your entire history

**Comment by justchokingaround** [comment]
oh yes, that would work as well
