### ISSUE TITLE
History keeps playing and its annoying

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#60]
Example use case I am 2 episodes behind The secret of skinwalker ranch season 4 (need to watch ep4 and ep5) but I selected 
ep5 instead of ep4.
![5](https://github.com/justchokingaround/lobster/assets/95531944/1ab0eeb7-bfd5-4f0b-b291-04d71957c342)
![6](https://github.com/justchokingaround/lobster/assets/95531944/dd6569ef-4fd5-4f1f-9fc7-37c44a71b1bc)

Ep5 plays and I immediately close it and cause I want to watch ep4 first instead.
![7](https://github.com/justchokingaround/lobster/assets/95531944/af98f820-cad5-4907-ae60-fe581f27e223)

Script asks me this and I want to search for season 4 ep 4 instead
![8](https://github.com/justchokingaround/lobster/assets/95531944/791d694a-bfc6-4c5f-910e-9d0306b6ebc9)

In the search menu I select the secret skinwalker ranch again
![9](https://github.com/justchokingaround/lobster/assets/95531944/de948a37-dca9-4d49-864f-748809f91b36)

Instead it plays the season 4  ep5  again and it doesnt even let me select which season or episode it just continue the history
![10](https://github.com/justchokingaround/lobster/assets/95531944/00d1bbc9-c212-4e54-bd95-5655d7fc41f3)

**Comment by ttx99** [comment]
imho we don't need history  file It's nice to have but I don't even use or rarely even back on v3

**Comment by ttx99** [comment]
Imho you should just think back like Lobster v3  but with:

Support for Thumbnail(ueberzuggupp)
Support for Trending and Recent TV show and Movies
Revert Back the Fzf menu with Number selection before the title

Simplicity rocks dude but this is just my own opinion

**Comment by ttx99** [comment]
I think that history should be explicitly enabled by user, rather that it enabled automatically.

**Comment by justchokingaround** [comment]
made history optional in https://github.com/justchokingaround/lobster/commit/766aaed841407e9c2cbb55f1dfe5ab69ccc9358c. that should also fix other issues

**Comment by ttx99** [comment]
> made history optional in [766aaed](https://github.com/justchokingaround/lobster/commit/766aaed841407e9c2cbb55f1dfe5ab69ccc9358c). that should also fix other issues

optional and off by default pls

**Comment by justchokingaround** [comment]
it is
