### ISSUE TITLE
[minor bug] .local/share/applications/lobster not used under fzf

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#63]
Under normal use with just fzf and no images. When you start, it creates the folder and when you finish it removes it, without ever using it.

I haven't tested ueberzugpp.

**Comment by justchokingaround** [comment]
i don't get the bug?

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/766aaed841407e9c2cbb55f1dfe5ab69ccc9358c
