### ISSUE TITLE
[bug] rofi menu has applications in it

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#64]
normal applications are in the menu (like gimp etc). 

I don't know what exactly you are trying to do, but this is obviously a glitch. And i don't see images in rofi, i'm assuming that's normal.

I'm in debian 11, maybe they configured the system differently.

If .local/share/applications/lobster is temporary, maybe it should be in /tmp too?

**Comment by justchokingaround** [comment]
if you configure the config file properly, that is set these values (this use my custom rofi configuration, check the README for more info):
```sh
use_external_menu=1
image_preview=1
image_config_path="$HOME/.config/rofi/styles/launcher.rasi"
```
you will get the entries looking like this during the selection menu:
![image](https://github.com/justchokingaround/lobster/assets/44473782/5de58282-b899-48ac-8df0-19345197db0e)

i cannot put it in temp, as rofi will not recognize the .desktop entries there as application
