### ISSUE TITLE
I don't know what is this?

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#65]
I dont know what is this and stream is slow

![1](https://github.com/justchokingaround/lobster/assets/95531944/d7792d57-9a71-48a5-b9de-46434bb05ecc)

**Comment by justchokingaround** [comment]
can you send me the logs please?
```
sh -x $(which lobster) the mother 2> lobster.log
```

**Comment by ttx99** [comment]
is the right command?

sh -x /usr/local/bin/lobster the mother 2> lobster.log

**Comment by justchokingaround** [comment]
yes

**Comment by ttx99** [comment]
is it normal for the process to be slow? I pressed enter and it's still not showing something

**Comment by ttx99** [comment]
right now 
![1](https://github.com/justchokingaround/lobster/assets/95531944/91f7a266-36aa-4eca-a876-a8e52bbf8b99)

**Comment by justchokingaround** [comment]
just spam enter until it's done, fzf might not show up since you're redirrecting stderr

**Comment by ttx99** [comment]
![2](https://github.com/justchokingaround/lobster/assets/95531944/3cd90446-8cbb-4aea-ad29-0693ae3dc401)

**Comment by justchokingaround** [comment]
in that case you have to imagine that the fzf menu shows up, type "the mother" and press enter (this will be invisible. after that send me the lobster.log file

**Comment by justchokingaround** [comment]
and then press enter, yes

**Comment by ttx99** [comment]
![2](https://github.com/justchokingaround/lobster/assets/95531944/b1342c31-1e2a-480c-a1b0-9b1476035b60)

**Comment by justchokingaround** [comment]
actually i'm getting the same error, this is a problem with the source's video stream, nothing i can do about it
