### ISSUE TITLE
Search result bug

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#68]
Search result bug
![1](https://github.com/justchokingaround/lobster/assets/95531944/7c489a86-cd8a-4579-adb7-a90ef5bf767e)

search result
![2](https://github.com/justchokingaround/lobster/assets/95531944/1eb0b96e-9c2f-4b87-b769-b4bd71d1bda8)

But it's there
![3](https://github.com/justchokingaround/lobster/assets/95531944/ea75100a-24f4-4556-9c36-231bf5154330)

**Comment by justchokingaround** [comment]
should be fixed in https://github.com/justchokingaround/lobster/commit/048833b83131262606afd4f7222f201e93e29074

**Comment by ttx99** [comment]
thanks bro
