### ISSUE TITLE
Please have this prompt asks user instead of the script exiting after watching a movie

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#69]
after watching a TV show
![1](https://github.com/justchokingaround/lobster/assets/95531944/3d4499fd-cf7d-4a0f-97af-c812c47b24dd)

after watching a movie it just exit
![2](https://github.com/justchokingaround/lobster/assets/95531944/0a61cdae-104c-4291-8d04-37472f804605)

**Comment by justchokingaround** [comment]
is that really wanted behavior? i assumed after a user completes a movie, he'd want to exit the script since movies are long

**Comment by justchokingaround** [comment]
alright, i'll add it in the next commit then

**Comment by justchokingaround** [comment]
added in https://github.com/justchokingaround/lobster/commit/09e427ddd72179d90b5c13e8626c339f25979a96
