### ISSUE TITLE
[feature] folder .local/share/lobster

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#70]
**Is your feature request related to a problem? Please describe.**
It's hard to move around user folders/files. The few bytes saved aren't worth the potential future difficulties.

**Describe the solution you'd like**
To avoid future problems of this sort, i would advise to have a folder  .local/share/lobster

**Describe alternatives you've considered**
The alternative, is that in the future this folder might need to be created, file extension changed etc... It's just makes things difficult.

**Comment by justchokingaround** [comment]
for what? i already use this folder for storing the history
