### ISSUE TITLE
[minor bug] lobster_history.txt: No such file or directory

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#71]
**Describe the bug**
error on start up
`grep: /home/XXX/.local/share/lobster_history.txt: No such file or directory`

when history is active, it just complain once. If history is inactive, the file never gets generated, so it always complain on startup.

**To Reproduce**

delete the file lobster_history.txt, then start with history active and with history inactive.

**Expected behavior**
It shouldn't complain that the file doesn't exist.

**Comment by justchokingaround** [comment]
should be fixed in https://github.com/justchokingaround/lobster/commit/67ead96d114d8d06e0d29ad66f9af2989a5d185b

**Comment by justchokingaround** [comment]
yeah, that's my bad, didn't test before pushing, sorry
fixed in https://github.com/justchokingaround/lobster/commit/09e427ddd72179d90b5c13e8626c339f25979a96
