### ISSUE TITLE
Print out year released for those who only use fzf 

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#73]
![1](https://github.com/justchokingaround/lobster/assets/95531944/04554348-d766-4c1a-9e63-e10e2d9325cd)

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/lobster/commit/b2c5d31bfda33780de77c91e98dc146402e3975c

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/5aef481c0dfc10fd56bf361d8f672a73a4b14d4b, i didn't realize duration wasn't supported by tv shows
