### ISSUE TITLE
Some Movies subtitles dont work

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#74]
subtitle not working in spiderman no way home 

in website
![3](https://github.com/justchokingaround/lobster/assets/95531944/3257d988-2c08-44e9-a302-c1bf80efc2a2)

in mpv
![5](https://github.com/justchokingaround/lobster/assets/95531944/43ea257f-354d-493b-b0b2-02e919ff33fe)

config:
history=0
use_external_menu=0
image_preview=0
image_config_path="$HOME/.config/rofi/styles/launcher.rasi"
subs_language="English"
player="mpv"
quality="1080"
provider="UpCloud"
json_output=0
histfile="$HOME/.local/share/lobster_history.txt"
cache_dir="/tmp/lobster"
images_cache_dir="/tmp/lobster-images"
applications_dir="$HOME/.local/share/applications/lobster"
tmp_position="/tmp/lobster_position"

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/b1edb522c9e4af529c6a291d14b31cb6c9c9d99e

**Comment by ttx99** [comment]
thanks bro
