### ISSUE TITLE
Pressing Yes to Continue? prompt just exits the script and doesnt resume the video

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#81]
![1](https://github.com/justchokingaround/lobster/assets/95531944/322a4f8e-c894-453f-97cb-004f7ede2284)

**Comment by ttx99** [comment]
for tv shows it works 
for movies it doesn't

**Comment by ttx99** [comment]
But I think the prompt should just ask if we want to search again or exit the script. 
I mean there is Lobster -c for that right?

**Comment by justchokingaround** [comment]
should be fixed in https://github.com/justchokingaround/lobster/commit/76fa8506dc89cb07fb18768160b382951e43762c please test and report back

**Comment by ttx99** [comment]
nice  thanks
