### ISSUE TITLE
Infinite loop when you just type lobster -p and forgot the provider name

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#84]
![1](https://github.com/justchokingaround/lobster/assets/95531944/27a850df-dd49-4635-a3d2-6e0105f83042)

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/76fa8506dc89cb07fb18768160b382951e43762c
(there are 2 supported providers: Vidcloud and UpCloud, i just forgor to add it to docs)
