### ISSUE TITLE
[feature] in cleanup() remove contents

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#85]
**Is your feature request related to a problem? Please describe.**
Removing the whole folder create issues with firejail.

**Describe the solution you'd like**
Only remove the contents.

**Describe alternatives you've considered**
Removing the folder forces you to allow editing in the parent folder.

**Comment by justchokingaround** [comment]
what is firejail and how is that a problem?

**Comment by justchokingaround** [comment]
ok, i will fix that in upcoming commits then

**Comment by justchokingaround** [comment]
done in 76fa8506dc89cb07fb18768160b382951e43762c
