### ISSUE TITLE
[FEATURE] download improvements

### ISSUE THREAD

**Issue by ghost** [justchokingaround/lobster#87]
**Is your feature request related to a problem? Please describe.**
1. ffmpeg just hangs if the network connection is lost. It's not really designed as a downloader.
2. When downloading, lobster just dumps it in the current directory.

**Describe the solution you'd like**
1. yt-dlp does a far better job at downloading and been able to resume. The website is not supported, but you can provide it with the m3u8. The command is something like this `yt-dlp -f 720 file.m3u8 --no-skip-unavailable-fragments --fragment-retries infinite -o file.mp4`
2. I would propose a configurable download folder, with the default probably ~/Downloads.

**Additional context**
yt-dlp has other options, like selecting the resolution and neet tools like embedding images.

**Comment by justchokingaround** [comment]
added the ability to define a custom download function in the config file in https://github.com/justchokingaround/lobster/commit/13e7506c2eedc164f63f332b548bc732cd0c5dbf
here is an example of what you can define in the config file, if you would like to use yt-dlp with 16 threads. the 1st argument passed to the function is the video link (the m3u8 source) and the 2nd one is the title of the movie or tv show episode
```sh
download_video() {
  yt-dlp "$1" --no-skip-unavailable-fragments --fragment-retries infinite -N 16 -o "$2".mp4
}
```
let me know if this works fine for you, i will add it to the documentation a bit later

**Comment by justchokingaround** [comment]
and i forgot about the image variable if it exists, i'll be adding it tomorrow

**Comment by justchokingaround** [comment]
added in https://github.com/justchokingaround/lobster/commit/320606608a578c2ac3e375bf994f6918243f2267
you can specify `download_dir` in the config file, or during runtime (just `-d <full-path>` or `-d <relative-path>` or just `-d` will also work, defaults to the current working directory). a new version of the custom download_video function would look like this:
```sh
download_video() {
  yt-dlp "$1" --no-skip-unavailable-fragments --fragment-retries infinite -N 16 -o "$3/$2".mp4
}
```
where $1 is the video link, $2 the title, $3 the path and $4 the thumbnail
