### ISSUE TITLE
Recently added movies and recently added tv show

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#88]
like the first page of https://flixhq.to/movie should be the recently added movies
and first page of https://flixhq.to/tv-show for tv shows

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/lobster/commit/99d970e7439183c7cf2510613a30650752472291
use `lobster -r` for movies and `lobster -r tv` for tv shows. explicitly defining `lobster -r movie` will also work

**Comment by justchokingaround** [comment]
(will document later)

**Comment by ttx99** [comment]
nice but dont include the upcoming movies cause people will be confused theres no video yet.
 
![1](https://github.com/justchokingaround/lobster/assets/95531944/046c9c42-2926-4341-9edb-2613e5754833)
![2](https://github.com/justchokingaround/lobster/assets/95531944/1583ddef-3cd8-41e5-a80f-fea549b43edd)
