### ISSUE TITLE
[DOC] AUR and MPR package

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#89]
for the REDME, lobster is in the AUR and MPR (like the AUR but for debs)
https://aur.archlinux.org/lobster.git
https://mpr.makedeb.org/packages/lobster-git

**Comment by justchokingaround** [comment]
did u mean this https://aur.archlinux.org/packages/lobster ?

**Comment by justchokingaround** [comment]
i flagged it out of date, so i will wait before adding that to the README. in the meantime, i will now make a `lobster-git` package and add it to the README with the debian package (and later on a homebrew formula). thank you for letting me know these even existed, i had no idea!

**Comment by justchokingaround** [comment]
![image](https://github.com/justchokingaround/lobster/assets/44473782/cb1b3b1e-1b3a-4737-be54-b7140ec087e9)
this is what im currently stuck on

**Comment by justchokingaround** [comment]
oh ok, i will try that later then

**Comment by justchokingaround** [comment]
it said in their docs that the easiest way to install it would be using their bash script:

![image](https://github.com/justchokingaround/lobster/assets/44473782/f5afc526-af3e-4347-a532-e07f37888502)

but if you say using apt is the preferred and more standard way for debian users, i can tell users to use that installation method instead

**Comment by justchokingaround** [comment]
awk and perl aren't dependencies for the script, please remove them

**Comment by justchokingaround** [comment]
added the debian instructions to the docs in 2d0024c013e2c5cb246f9349f6cf120929bd48f9
please make socat an optional dependency as well @pirate486743186 (it is used when history is enabled, but that feature is disabled by default)
