### ISSUE TITLE
Program not found

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#91]
![1](https://github.com/justchokingaround/lobster/assets/95531944/b5c5fbd6-75f4-4198-b855-1bb1730aa6fe)

**Comment by justchokingaround** [comment]
send me the logs please:
```sh
sh -x $(command -v lobster) 2> log
```

**Comment by ttx99** [comment]
![1](https://github.com/justchokingaround/lobster/assets/95531944/5b64140a-1e54-4d87-b387-663681b2e1f7)

**Comment by justchokingaround** [comment]
send me the `log` file

**Comment by ttx99** [comment]
where do i find it?

**Comment by justchokingaround** [comment]
in the current working directory

**Comment by ttx99** [comment]
it says file type not supported when i drag it here

**Comment by ttx99** [comment]
here is the content though

+ LOBSTER_VERSION=3.9.9
+ config_file=/home/mac99/.config/lobster/lobster_config.txt
+ lobster_editor=/usr/bin/nano
+ case "$(uname -s)" in
++ uname -s
+ separator=:
+ path_thing='\'
+ command -v notify-send
+ notify=true
+ command -v socat
+ socat_exists=true
+ command -v hxunent
+ dep_ch grep '' curl fzf mpv socat
+ for dep in "$@"
+ command -v grep
+ command -v grep
+ for dep in "$@"
+ command -v ''
+ send_notification 'Program "" not found. Please install it.'
+ '[' '' = 1 ']'
+ '[' '' = 0 ']'
+ '[' '' = '' ']'
+ '[' -z '' ']'
+ printf '\33[2K\r\033[1;34m%s\n\033[0m' 'Program "" not found. Please install it.'
+ return
+ command -v ''
+ exit 1

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/886818ef6528765098e1c93a75957909e69c1c08
i did an oopsie doopsie while adding mac support

**Comment by ttx99** [comment]
i think i need to uninstall first

![1](https://github.com/justchokingaround/lobster/assets/95531944/10564dc6-6ee9-45be-9773-9acfe387f10b)

**Comment by justchokingaround** [comment]
yes, you do, sorry about that
