### ISSUE TITLE
lobster -p "Vidcloud" just freezes

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#92]
![1](https://github.com/justchokingaround/lobster/assets/95531944/b2be5444-fb20-43a3-986a-f9f06c05d725)

**Comment by ttx99** [comment]
and lobster -p "UpCloud" too

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/13e7506c2eedc164f63f332b548bc732cd0c5dbf
