### ISSUE TITLE
[feature] support ueberzug

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#93]
**Is your feature request related to a problem? Please describe.**
ueberzug doesn't work out of the box. ueberzugpp is great, but it's not packaged in distributions. ueberzug is packaged in debian and ubuntu. Also ueberzug has a fork now, so it isn't dead.

**Describe the solution you'd like**
support also ueberzug.

**Comment by justchokingaround** [comment]
i don't plan on doing that, since i don't think it's a reliable idea in the long run. i made an issue in the ueberzugpp repo for the packages: https://github.com/jstkdng/ueberzugpp/issues/48
