### ISSUE TITLE
Dont include the coming soon videos  cause theyre not out yet and movies in command lobster -r tv.

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#94]
lobster -r tv dont include the upcoming videos cause theyre not out yet.

![1](https://github.com/justchokingaround/lobster/assets/95531944/c63d05bb-f982-4fba-a14e-5b836599969c)
![2](https://github.com/justchokingaround/lobster/assets/95531944/1020e716-e6bf-4998-bc93-51ecf44ddf78)

**Comment by ttx99** [comment]
I thin contents of lobster -r tv should be https://flixhq.to/tv-show

**Comment by justchokingaround** [comment]
yes, and i see no point in scraping the coming soon tv shows/movies as they're not out on the website yet...

**Comment by justchokingaround** [comment]
https://flixhq.to/tv-show is what i'm scraping tho, can u give an example of a tv show that doesn't work?

**Comment by ttx99** [comment]
the search results actually included for example The Marvels which is yet to be releases this November. Thats a marvel movie

**Comment by ttx99** [comment]
These are not yet out but for some reason flixhq choose to showcase their thumbnails.
![1](https://github.com/justchokingaround/lobster/assets/95531944/8233d73f-8608-47bd-8d8e-e665b96f9a4c)

**Comment by justchokingaround** [comment]
are you sure you are on the latest commit, i can't reproduce this?

**Comment by ttx99** [comment]
![1](https://github.com/justchokingaround/lobster/assets/95531944/3dddde6a-b0c2-4f19-86a3-de1f24ec87e8)
![2](https://github.com/justchokingaround/lobster/assets/95531944/682bb172-ef41-4a32-b59b-4fa12b0e2dac)
![3](https://github.com/justchokingaround/lobster/assets/95531944/93a876ac-74ae-4309-ab49-feb616f7a8e5)

**Comment by justchokingaround** [comment]
can you uninstall completely and reinstall again, please?
```
sudo rm $(command -v losbter)
sudo curl -sL github.com/justchokingaround/lobster/raw/main/lobster.sh -o /usr/local/bin/lobster &&
sudo chmod +x /usr/local/bin/lobster
```

**Comment by ttx99** [comment]
![1](https://github.com/justchokingaround/lobster/assets/95531944/a81b941c-d590-4634-af30-71fc103d5acf)
![2](https://github.com/justchokingaround/lobster/assets/95531944/7e66b770-4672-4d36-86ed-534c66cd3530)

**Comment by ttx99** [comment]
after the script just exits after selecting video
![1](https://github.com/justchokingaround/lobster/assets/95531944/f27a3943-652f-4aaa-a6d7-a98c0a600a24)
![2](https://github.com/justchokingaround/lobster/assets/95531944/c844b65a-c0c1-4ad2-83f6-28546ea83be2)
![3](https://github.com/justchokingaround/lobster/assets/95531944/7fd9300f-2411-4003-b677-f1a72bc2a654)

**Comment by justchokingaround** [comment]
can you update to the latest version, and then run it using `lobster -x -r tv` please, that should output the logs to the terminal and also save them in `/tmp/lobster.log` which i'd be interested in
i cannot reproduce this behavior:
![image](https://github.com/justchokingaround/lobster/assets/44473782/043e6cbc-c96d-4316-a2a2-8d412bc07bf0)

**Comment by ttx99** [comment]
[lobster.log](https://github.com/justchokingaround/lobster/files/11581770/lobster.log)

**Comment by justchokingaround** [comment]
3856d15 should fix it, i missed a line when refactoring, sorry about that, please test it

**Comment by ttx99** [comment]
fixed thx
![4](https://github.com/justchokingaround/lobster/assets/95531944/f375678d-5f8e-42a3-b3a8-2829abe08d79)

**Comment by justchokingaround** [comment]
yes sorry about all the chokes, just a lot to keep in mind, and i miss stuff quite often

**Comment by ttx99** [comment]
lol we the regular users should be thanking you for this wtf we cant code for shit.
