### ISSUE TITLE
/tmp organization

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#96]
1. put all your /tmp stuff inside /tmp/lobster.
2. symlink $HOME/.local/share/applications/lobster inside /tmp/lobster (i mean, the files are actually in tmp)
3. At shutdown, you just purge /tmp/lobster , do you even need a function for this?

This would be far better then how it is now.

**Comment by justchokingaround** [comment]
symlinking each .desktop file individually would be less efficient and i don't see what i gain by doing this

**Comment by justchokingaround** [comment]
so create an applications dir, inside of `/tmp/lobster` and symlink it to `~/.local/share/applications/` ? again, i don't get what i gain from this, it just seems to complicate things

**Comment by justchokingaround** [comment]
did that in 7eb4b02
