### ISSUE TITLE
lobster -d rick and morty saves in ./rick

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#98]
it always need a parameter. Unless you put -d at the end.

download_dir from the config file is never used.

**Comment by justchokingaround** [comment]
you pass `rick` as the download_dir and `and morty` as the query parameter. if you want to download in the current working dir, either use `lobster rick and morty -d` or `lobster -d` and then look up the episode u need
(i just realized that this is a type in the README, i will fix it now)

**Comment by justchokingaround** [comment]
fix in e30f50c33517e3a242753de0e2286c3af34434fb
and i agree that `-d .` is more elegant, pushing changes for that now
