### ISSUE TITLE
lobster -t tv

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#99]
![1](https://github.com/justchokingaround/lobster/assets/95531944/77acd190-c882-48a2-ba9b-3f1561eaa285)

**Comment by justchokingaround** [comment]
is it really worth it to separate tv and movies for trending? i did it for recent because they were on 2 separate pages, and i couldn't get them with one request

**Comment by ttx99** [comment]
well, probably not right but if other users ask for it will it be possible?

**Comment by justchokingaround** [comment]
sure, if that's what is preferred. i'll be closing it as not planned for the time being
